### ISSUE TITLE
Integrate with JuliaML

### ISSUE THREAD

**Issue by tbreloff** [malmaud/TensorFlow.jl#1]
Hi @malmaud do you have time/interest to get this package working with the building blocks of JuliaML?  Similar to my strategy with Plots, I think it would be a good first step to fine-tune the API of JuliaML using an existing "backend" like TensorFlow.  Specifically I'd like to wrap the building of TF networks using the stuff I'm experimenting with in Transformations.jl (tom branch).

I guess you don't need to help much with the coding, but it would be good to know if I can bug you with occasional questions about the package.  Thanks

**Comment by malmaud** [comment]
I think for me personally, I'll just be satisfied replicated the Python Tensorflow API with some Julia niceties. I would have no opposition to someone else working on integrating it with JuliaML, though.

**Comment by tbreloff** [comment]
Cool... No opposition is good enough for me. :)

**Comment by malmaud** [comment]
I think I'll close this for now since there doesn't seem be an action item for me. Looking forward to seeing the eventual integration, though.
