### ISSUE TITLE
concat uses python indexing (zero based) for dimension

### ISSUE THREAD

**Issue by baggepinnen** [malmaud/TensorFlow.jl#101]
```
session = Session(Graph())
a_ = placeholder(Float32, shape=[-1,1])
s_ = placeholder(Float32, shape=[-1,2])
sa = concat(1, [s_,a_]) 
run(session,sa, Dict(s_=> [1.,1.]', a_=>[1.]'))
```

ERROR: LoadError: Tensorflow error: Status: ConcatOp : Expected concatenating dimensions in the range [0, 2), but got 2

This code also produces an error when showing the `sa`-tensor in the REPL

**Comment by malmaud** [comment]
Hmm, that exact code works for me. Sure you're on the latest version?

**Comment by malmaud** [comment]
This works now, so I'm going to close.
