### ISSUE TITLE
Define `size` for things with `get_shape`

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#102]
`get_shape` seems to be TensorFlow for `Base.size`.
But with the ability for it to be unknown etc.

Eg
```
get_shape(Ts) 
Out[93]:
TensorShape[407, 16]
In [96]:

get_shape(X_ids)
Out[96]:
TensorShape[unknown]
```

Does it makes sense to define a overload for `Base.size`, that returns a tuple of `Ints`, or throws an exception if the size is unknown?

**Comment by malmaud** [comment]
I'm reluctant to do that since `size(::Tensor)` already has a meaning in Julia - the Julia 'size' of any non-container object is `()` and it could get confusing to alter that meaning for tensors. But I am open to counter-arguments.

**Comment by IainNZ** [comment]
+1 for not conflating the two, the details are sufficiently different that I think it could only be confusing.

**Comment by malmaud** [comment]
OK, I'll close for now.
