### ISSUE TITLE
LoadError: Tensorflow error: Status: NodeDef mentions attr 'T' not in Op

### ISSUE THREAD

**Issue by zahachtah** [malmaud/TensorFlow.jl#104]
Using the example on the first page of the GitHub repo I get an error when running the following line:

```julia
minimize_op = train.minimize(optimizer, Loss)
```

LoadError: Tensorflow error: Status: NodeDef mentions attr 'T' not in Op<name=BroadcastGradientArgs; signature=s0:int32, s1:int32 -> r0:int32, r1:int32>; NodeDef: gradients/node11_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32](gradients/node11_grad/Shape, gradients/node11_grad/Shape_1)

while loading In[5], in expression starting on line 4

 in check_status(::TensorFlow.Status) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/core.jl:107
 in TensorFlow.Operation(::TensorFlow.NodeDescription) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/core.jl:400
 in TensorFlow.Operation(::TensorFlow.tensorflow.NodeDef) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/core.jl:613
 in extend_graph(::TensorFlow.Graph, ::Array{Any,1}) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/core.jl:82
 in gradients(::TensorFlow.Tensor, ::Array{Any,1}) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/core.jl:1037
 in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor, ::Void) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/train.jl:46
 in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/train.jl:38
 in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /Users/Raukhur/.julia/v0.5/TensorFlow/src/train.jl:35

**Comment by malmaud** [comment]
Hmm, try `Pkg.checkout("TensorFlow")` and then `Pkg.build("TensorFlow")`

**Comment by malmaud** [comment]
Let me know if you're still having issues

**Comment by zahachtah** [comment]
Not entirely sure, had to reinstall and never installed tensor flow again, trying juliaML at the moment. So closing, and thanks for all help, will surely start using it again in the future
