### ISSUE TITLE
libtensorflow.so issues when precompiling

### ISSUE THREAD

**Issue by Godisemo** [malmaud/TensorFlow.jl#106]
I've been having trouble precompiling this package with GPU support, getting error messages like

```
INFO: Precompiling module TensorFlow.
WARNING: could not import Base.lastidx into LegacyStrings

signal (11): Segmentation fault
while loading /home/calle/.julia/v0.5/TensorFlow/src/TensorFlow.jl, in expression starting on line 132
unknown function (ip: 0x7f8e7e37348f)
unknown function (ip: 0x63e6278aec9fefb6)
Allocations: 5125614 (Pool: 5124555; Big: 1059); GC: 7
ERROR: Failed to precompile TensorFlow to /home/calle/.julia/lib/v0.5/TensorFlow.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
```

After digging and doing some research I think I might have solved it by compiling my own libtensorflow.so and replacing the one downloaded by this package during build.

For anyone else having trouble like this, my  process was as follows:
- clone the tensorflow repository https://github.com/tensorflow/tensorflow and don't forget to check out the correct tag! in my case `git checkout tags/v0.11.0`
- install build dependencies as described on https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources
- run `./configure` in the tensorflow repo and follow instructions. In my case I chose to configure with cuda 8.0 and compute capability 6.1.
- build tensorflow library with the command `bazel build -c opt --config=cuda tensorflow:libtensorflow_c.so`
- finally, replace `$HOME/.julia/v0.5/TensorFlow/deps/usr/bin/libtensorflow_c.so`with the library you just compiled, which is located in `bazel-bin/tensorflow/tensorflow_c.so`

The thing is, while shipping precompiled libraries with this julia package is convenient, it is prone to give errors for some users which use incompatible hardware/software configurations. I would suggest one of two things (or both)
- add build instructions like these in the documentation
- automate building of different versions of the libraries and making sure the correct one will download when installing this package.

**Comment by malmaud** [comment]
Automatic building sounds like a pretty thorny problem. For now, I think it's a good idea to go with adding the instructions.

**Comment by Godisemo** [comment]
What do you think is causing the issues for me? My cuda version, compute capability or something completely different?

**Comment by malmaud** [comment]
It could well be the cuda version. The pre-included binaries were compiled against 7.5, so if you have 8, I could see that being a problem. I've never tested that.

**Comment by Godisemo** [comment]
Sounds reasonable. So a light weight version of automatic building could be to compile at least for different cuda versions?

**Comment by malmaud** [comment]
Ya, that would be fine. Not sure when I can get around to implementing that myself, though.

**Comment by oschulz** [comment]
I just ran into the same problem - CUDA-8.0 support would be great. ArrayFire, for example, requires CUDA-8 now.

**Comment by malmaud** [comment]
Alright, I can build binaries against CUDA 8.0. Then maybe add a new environment variable configuration option like `TF_USE_GPU_CUDA_8` for users to install it with when doing `Pkg.build`.

**Comment by Godisemo** [comment]
I got the impression that cuda  8 support vas just recently introduced in the latest version of tensorflow, 0.11.0. Maybe it would be possible to autodetect which version of cuda users have installed. Otherwise the environment variable is good for now.

**Comment by oschulz** [comment]
Thanks, @malmaud, that would be great! I think an environment variable will do fine for now. I like the idea of @Godisemo of auto-detecting the CUDA version - I wonder how complicated that would be?

**Comment by oschulz** [comment]
@malmaud: One suggestion: Maybe call env_variables `JULIA_TF_...`? Could make things a bit clearer if someone sees a shell script of a colleague, and wonders what the variables are for.

**Comment by Godisemo** [comment]
you can detect cuda library version with the following snippet

```
a = Cint[0]
ccall((:cudaDriverGetVersion, :libcudart), Void, (Ptr{Cint},), a) # you can also use :cudaRuntimeGetVersion
version = a[1]
```

I get 8000 for cuda version 8.0

**Comment by mdpradeep** [comment]
I am getting the same issue on a mac.
```
ulia> using TensorFlow
INFO: Precompiling module TensorFlow.

signal (11): Segmentation fault: 11
while loading /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/pkgs-0.5.0.4/v0.5/TensorFlow/src/TensorFlow.jl, in expression starting on line 133
unknown function (ip: 0xffffffffffffffff)
Allocations: 4624675 (Pool: 4623671; Big: 1004); GC: 6
ERROR: Failed to precompile TensorFlow to /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/pkgs-0.5.0.4/lib/v0.5/TensorFlow.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /Applications/JuliaPro-0.5.0.4.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
```

**Comment by JobJob** [comment]
@mdpradeep when compiling a tensorflow .so/.dylib myself on mac, I had to add my CUDA lib path to my LD_LIBRARY_PATH (I think, can't recall 100% - it's possible this may have only been an issue when running in Atom/Juno). Anyway, see [this comment](https://github.com/malmaud/TensorFlow.jl/issues/103#issuecomment-263168745) for more details.

**Comment by mdpradeep** [comment]
I just did the following and it worked. It looks there is an issue with `MbedTLS` library. I did the following:
```
ENV["FORCE_BUILD"]="true"
Pkg.build("TensorFlow")
Pkg.test("TensorFlow")
```
This went through fine.

**Comment by malmaud** [comment]
We now use the official upstream TensorFlow binaries.
