### ISSUE TITLE
shape_inference of split

### ISSUE THREAD

**Issue by karenl7** [malmaud/TensorFlow.jl#113]
I suspect a possible typo. `spit_dim` is not defined.
https://github.com/malmaud/TensorFlow.jl/blob/master/src/shape_inference.jl#L452

**Comment by malmaud** [comment]
Fixed in https://github.com/schmrlng/TensorFlow.jl/commit/12a1f1a2a3ed17bdebfcda7f2c1bbd168e01c03a
