### ISSUE TITLE
`permutedims` as a alias for `transpose`?

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#121]
The way `transpose` work on TensorFlow is how `permutedims` works in normal julia.
should it thus be aliased?

`tranpose`, right now uses 0 based indexing,
Would a `permutedims` use 1 Based indexing?
Is this a convention established by `argmax` and `indmax` ?

**Comment by malmaud** [comment]
Sure, that's a good idea. I was trying to keep things as 1-based as reasonable to keep things consistent with the rest of Julia .
