### ISSUE TITLE
 Op Inv is not available in GraphDef version 20

### ISSUE THREAD

**Issue by MikeInnes** [malmaud/TensorFlow.jl#123]
I get this error doing `Pkg.test()` on both master and the latest release, after `Pkg.build("TensorFlow")` and `pip install --upgrade tensorflow`. I guess it must be due to Python side TF being out of date and putting `Inv` in the gradient graph, but upgrading to 0.12.1 hasn't helped – do I need to be on master or something?

**Comment by malmaud** [comment]
Are you sure your `PyCall` is pointing to the Python distribution that has TensorFlow .12?

**Comment by MikeInnes** [comment]
Great shout, that was exactly the issue (I have no memory whatsoever of changing PyCall to Python 3 or installing tensorflow there though... weird).
