### ISSUE TITLE
problems with TensorFlow 0.10.0 (some func names have changed)

### ISSUE THREAD

**Issue by philtomson** [malmaud/TensorFlow.jl#128]
I've got TensorFlow 0.10.0 installed. Apparently some function names have changed in TensorFlow 0.10.0, when I tried to run your Logistic Regression example code I get:

> julia> minimize_op = train.minimize(optimizer, Loss)
> ERROR: Tensorflow error: Status: Op Inv is not available in GraphDef version 20. It has been removed in version 17. Use Reciprocal.
> 
>  in check_status(::TensorFlow.Status) at /home/phil/.julia/v0.5/TensorFlow/src/core.jl:101
>  in TensorFlow.Operation(::TensorFlow.NodeDescription) at /home/phil/.julia/v0.5/TensorFlow/src/core.jl:488
>  in TensorFlow.Operation(::TensorFlow.tensorflow.NodeDef) at /home/phil/.julia/v0.5/TensorFlow/src/core.jl:678
>  in extend_graph(::TensorFlow.Graph, ::Array{Any,1}) at /home/phil/.julia/v0.5/TensorFlow/src/core.jl:79
>  in gradients(::TensorFlow.Tensor, ::Array{Any,1}) at /home/phil/.julia/v0.5/TensorFlow/src/core.jl:951
>  in compute_gradients(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor, ::Void) at /home/phil/.julia/v0.5/TensorFlow/src/train.jl:46
>  in #minimize#1(::Void, ::Void, ::String, ::Function, ::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/phil/.julia/v0.5/TensorFlow/src/train.jl:38
>  in minimize(::TensorFlow.train.AdamOptimizer, ::TensorFlow.Tensor) at /home/phil/.julia/v0.5/TensorFlow/src/train.jl:35

I poked around a bit and found this in TensorFlow.jl/src/ops/math.jl:

```
for (jl_func_name, tf_func_name) in [
    (:inv, "MatrixInverse"),
    (:det, "MatrixDeterminant"),
    (:diagm, "Diag"),
    (:diag, "MatrixDiagPart")]
    @eval function Base.$jl_func_name(n::AbstractTensor; name=$tf_func_name)

```

Tried changing that to:
```
 
for (jl_func_name, tf_func_name) in [
    (:reciprocal, "MatrixInverse"),
    (:det, "MatrixDeterminant"),
    (:diagm, "Diag"),
    (:diag, "MatrixDiagPart")]
    @eval function Base.$jl_func_name(n::AbstractTensor; name=$tf_func_name)

```

But that gives:

> julia> using TensorFlow
> INFO: Precompiling module TensorFlow.
> ERROR: LoadError: LoadError: LoadError: UndefVarError: reciprocal not defined
>  in macro expansion; at /home/phil/.julia/v0.5/TensorFlow/src/ops/math.jl:291 [inlined]
>  in anonymous at ./<missing>:?
>  in include_from_node1(::String) at ./loading.jl:488 (repeats 3 times)
>  in macro expansion; at ./none:2 [inlined]
>  in anonymous at ./<missing>:?
>  in eval(::Module, ::Any) at ./boot.jl:234
>  in process_options(::Base.JLOptions) at ./client.jl:239
>  in _start() at ./client.jl:318
> while loading /home/phil/.julia/v0.5/TensorFlow/src/ops/math.jl, in expression starting on line 285
> while loading /home/phil/.julia/v0.5/TensorFlow/src/ops.jl, in expression starting on line 126
> while loading /home/phil/.julia/v0.5/TensorFlow/src/TensorFlow.jl, in expression starting on line 130
> ERROR: Failed to precompile TensorFlow to /home/phil/.julia/lib/v0.5/TensorFlow.ji.
>  in compilecache(::String) at ./loading.jl:593
>  in require(::Symbol) at ./loading.jl:422

**Comment by malmaud** [comment]
Ya, you're going to want to use the latest version of both this package (via `Pkg.update(); Pkg.build("TensorFlow")` and the python tensorflow (`pip install --upgrade tensorflow`).
