### ISSUE TITLE
List of places where 0 based indexing persists

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#139]
For my own reference, and in preparation for some future PR.

A list of places where 0 based indexing persist.

- [x] slice
- [x] expand_dims
- [ ]  `argmax`, `argmin`
- [ ]  `where`
- [x] `indmax`, `indmin` results.

**Comment by oxinabox** [comment]
expand_dims
https://github.com/malmaud/TensorFlow.jl/pull/141

**Comment by malmaud** [comment]
Any others?

**Comment by oxinabox** [comment]
- [ ]  `argmax`, but that has the 1-based equiv: `indmax`
- [ ]  `where`, but that has the 1-bases equiv: `find`

**Comment by oxinabox** [comment]
Actually the results of `indmin`, and `indmax`  are still 0 based.

**Comment by oxinabox** [comment]
Closing this, due to any issue with this now being instead generated code issues.
And thus being more worthy of own issue
