### ISSUE TITLE
Issues initializing variables with VAE

### ISSUE THREAD

**Issue by IainNZ** [malmaud/TensorFlow.jl#14]
Here is a far-from-minimal reproducible example:
https://gist.github.com/IainNZ/541e8add942a436d813ebdfccc16b96c

I'm running on TensorFlow.jl master, TF CPU version.

```
ERROR: LoadError: Tensorflow error: Status: Must specify at least one target to fetch or execute.

in check_status(::TensorFlow.Status) at /Users/idunning/.julia/v0.5/TensorFlow/src/core.jl:114
in run(::TensorFlow.Session, ::Array{TensorFlow.Port,1}, ::Array{Any,1}, ::Array{TensorFlow.Port,1}, ::Array{Any,1})
```

**Comment by malmaud** [comment]
The problem is the call to `Graph()` creates a new default graph, so all the graph construction calls prior to line 122 are wiped out. Since the graph is empty, the call to `initialize_all_variables` fails. Admittedly that error could better, but just remove the call to `Graph` and the code works.

**Comment by IainNZ** [comment]
Ahh right. I copy-pasted that `Graph()` part from the minist_simple example, figuring it was something required for TF.jl

**Comment by malmaud** [comment]
Empty `run` invocations handled now via https://github.com/malmaud/TensorFlow.jl/commit/423f6c2a67695b83f0c650401e4af3811b400cff

**Comment by IainNZ** [comment]
Can you not do this:
```
cur_objective, _ = tf.run(sess, [objective, train_step],
                                  Dict(input_ph=>batch[1],
                                       normal_ph=>normal_sample))
```
?
```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{TensorFlow.Tensor,1} to an object of type TensorFlow.Port
This may have arisen from a call to the constructor TensorFlow.Port(...),
since type constructors fall back to convert methods.
 in TensorFlow.Port(::Array{TensorFlow.Tensor,1}) at ./sysimg.jl:53
 in collect_to!(::Array{TensorFlow.Port,1}, ::Base.Generator{Array{Any,1},Type{TensorFlow.Port}}, ::Int64, ::Int64) at ./array.jl:337
```

**Comment by malmaud** [comment]
The `train_step` is itself a vector of operations so `[objective, train_step]` is a nested type. Using `vcat` should work for now. I should wrap all the training steps into a single operation though.

**Comment by IainNZ** [comment]
Ah neat. Now just to figure out why it isn't working, then I'm set.

**Comment by IainNZ** [comment]
And I need to figure out I can submit opensource code...

**Comment by IainNZ** [comment]
Ah uint8s for mnist, seems to be OK with that fixed to [0,1] MNIST.

**Comment by malmaud** [comment]
Would be cool to have this example in the repo, if you are ok with that.

**Comment by IainNZ** [comment]
Oh yeah, definitely. I wanted to get plotting working, unfortunately pyplot imshow just blocks and never returns on my install so... any alternatives?

**Comment by malmaud** [comment]
plotly is the future of julia plotting man

**Comment by tbreloff** [comment]
@IainNZ I'd love to discuss Plots recipes for training monitoring.  I'm starting to focus on that myself.  Here's a very simple sample:  https://github.com/tbreloff/AtariAlgos.jl#example.  The gist is that it might be nice to have recipes for subplots, say tracking the ELBO, and then you could just combine them however you want into a custom layout.

And +1 to plotly... it's very nice.  Though I wouldn't ignore all the other great options... GR and GLVisualize for example.  Each has its place... depends on your workflow.

**Comment by malmaud** [comment]
Soon tensorflow.jl will support Tensorboard, so that's one solution for visualizing learning and graph structure.
