### ISSUE TITLE
Having more than one Session causes Constants to be wrong

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#140]
The constants seem to be getting their shape (and presumably value) from the constants in the previous session.
I'm pretty sure this wasn't happening a week ago.

This bug was really hard to track down. It is on current master with Julia 0.5.
It is caused by hidden global state of some kind, so a MWE was hard to make.

MWE:

```julia
using TensorFlow
prior_sess = Session(Graph())
A=constant(rand(4,5))
M = constant(rand(80))

sess = Session(Graph())
println("---------------")
@show dummy = get_variable("dummy",  [50, 10], Float32)
@show get_shape(dummy)
println("---------------")
@show dummy2 = get_variable("dummy2",  [50, 10], Float32)
@show get_shape(dummy2)
println("---------------")
@show good = get_variable("good",  [50, 10], Float32)
@show get_shape(good)
println("---------------")
```

Output:

```
first session all is well
A = constant(rand(4,5)) = <Tensor Const:1 shape=(4, 5) dtype=Float64>
get_shape(A) = TensorShape[4, 5]
M = constant(rand(80)) = <Tensor Const_2:1 shape=(80) dtype=Float64>
get_shape(M) = TensorShape[80]
second session, NOT OK
---------------
dummy = get_variable("dummy",[50,10],Float32) = TensorFlow.Variable(<Operation 'dummy'>,<Operation 'dummy/Assign'>)
get_shape(dummy) = TensorShape[4, 5]
---------------
dummy2 = get_variable("dummy2",[50,10],Float32) = TensorFlow.Variable(<Operation 'dummy2'>,<Operation 'dummy2/Assign'>)
get_shape(dummy2) = TensorShape[80]
---------------
good = get_variable("good",[50,10],Float32) = TensorFlow.Variable(<Operation 'good'>,<Operation 'good/Assign'>)
get_shape(good) = TensorShape[50, 10]
---------------
```

I have isolated the location of the error down to 
https://github.com/malmaud/TensorFlow.jl/blob/ff3bb9a0829794a66d8d7af0fcb53ddf81915f20/src/ops/sequences.jl#L12

In the definition of `constant`.
The `RawTensor` is fine and correct.
But the result of `Tensor(Operation(desc), 1)`
reports the wrong shape (when I hit it with `get_shape` before returning it from the `constant` function).

 I'm sorry I can't isolate it more, it is 2am and beyond that things get very ccall-y. 😴 

NB: I have removed the `tensorflow/core/platform/cpu_feature_guard.cc:45]` warnings from the output for readability; I believe unrelated.

**Comment by malmaud** [comment]
In the `meta-graph` branch (soon to be merged), I've moved all global state, including the constant shape information, to be properties of a particular graph.

**Comment by oxinabox** [comment]
I am looking forward to that then.
Because right now this breaks all interactive use.
Since re-declaring a modified version a system, in a new Session
also triggers this.

Which in today's case gave a the confounding effect of the second element of `reshape.(Xs, [[batch_size]])` being different to the rest.

I'll just go write some shape inference code til then.

**Comment by malmaud** [comment]
OK, the master branch has what should be a fix to this. Let me know if it's still an issue, though.
