### ISSUE TITLE
KeyError: key "SrcT" not found in extend_graph

### ISSUE THREAD

**Issue by baggepinnen** [malmaud/TensorFlow.jl#152]
I seem to have run into problems with the latest master (error output below). 

The line that throws the error is 
`∇aQ         = TensorFlow.gradients(q,[a_])[1] `
with 
```
julia> a_
<Tensor placeholder_2:1 shape=unknown dtype=Float64>
julia> q
<Tensor matmul:1 shape=(?, 1) dtype=Float64>
```
Unfortunately, my attempts at a minimal example have not been successful, so it must be a complicated interaction that leads to the error. Any more info useful?
```
ERROR: LoadError: KeyError: key "SrcT" not found
 in getindex at ./dict.jl:688 [inlined]
 in extend_graph(::TensorFlow.Graph, ::Array{Any,1}) at /local/home/fredrikb/.julia/v0.5/TensorFlow/src/core.jl:207
 in gradients(::TensorFlow.Tensor, ::Array{TensorFlow.Tensor,1}) at /local/home/fredrikb/.julia/v0.5/TensorFlow/src/core.jl:1046
 in get_apply_policy_gradient(::Array{TensorFlow.Variable,1}, ::TensorFlow.Tensor, ::TensorFlow.Tensor, ::TensorFlow.Tensor) at /work/fredrikb/reinforcementlearning/layers.jl:22
 in include_from_node1(::String) at ./loading.jl:488
while loading /work/fredrikb/reinforcementlearning/layers.jl, in expression starting on line 136
```

**Comment by oxinabox** [comment]
I would guess closely related to: https://github.com/malmaud/TensorFlow.jl/issues/147

**Comment by malmaud** [comment]
I have a change to upstream TensorFlow that's going to end these gradient-related problems once and for all.

**Comment by malmaud** [comment]
I think https://github.com/malmaud/TensorFlow.jl/pull/154 closes it, but let me know if not.
