### ISSUE TITLE
How to generate `libtensorflow_c.so`?

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#153]
It would be nice to have some docs on how to generate `libtensorflow_c.so`.
I need to build it myself, as the machine I am on  needs to stay on CUDA 7.5, 
so some matlab package someone else in the lab is using doesn't break.

I have gotten as far as compiling Python TensorFlow 1.0 but no `libtensorflow_c.so`. has been output.

**Comment by malmaud** [comment]
I'll write some docs, but the tldr is `bazel build //tensorflow:libtensorflow_c.so` and then it's in `bazel_bin/tensorflow`
