### ISSUE TITLE
using the right GPU (workaround)

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#156]
As far as I can tell there is not yet any equiv of the python `with device("gpu/1")`.

By default TensorFlow will put everything on `gpo/0`.
In theory this should be the fasted GPU by default.
But it can be screwed up, eg because the Tesla K40 has so much more RAM than the faster clocked  GTX 960.

Anyway, I found that everything was being put on `gpo/0` which was the GTX 960.

One can check this by doing:

```
julia> using TensorFlow

julia> con=TensorFlow.tensorflow.ConfigProto(;log_device_placement=true)
TensorFlow.tensorflow.ConfigProto(#undef,0,0,true,#undef,0,#undef,#undef,false,true,#undef,139661180041584)

julia> sess = Session(Graph(), con)
2017-02-25 17:18:38.689232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)
2017-02-25 17:18:38.689300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K40c, pci bus id: 0000:02:00.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0
/job:localhost/replica:0/task:0/gpu:1 -> device: 1, name: Tesla K40c, pci bus id: 0000:02:00.0
2017-02-25 17:18:38.691394: I tensorflow/core/common_runtime/direct_session.cc:257] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0
/job:localhost/replica:0/task:0/gpu:1 -> device: 1, name: Tesla K40c, pci bus id: 0000:02:00.0

Session(Ptr{Void} @0x00007f0565dbc990)
```

That is bad, because the K40 is a whole lot nicer (at least in theory) than the GTX.
So rather want to use it.

So the work around is to [tell CUDA to only see the K40](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars).
This is done by setting the environment variable `CUDA_​VISIBLE_​DEVICES`
to the UUID of the preferred GPU.
UUIDs can be found using the commandline program `nvidia-smi -L`
 

I figure this issue can stay open, to inform others, until GPU selection is added.
Which I don't see as a pressing feature.
Or I could write a documentation PR

**Comment by malmaud** [comment]
It should be quite an easy change, I'll get to it soon.
