### ISSUE TITLE
LSTMCell does not work with dynamic_rnn

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#179]
`GRUCell` works fine and `BasicRNNCell` work.
But not `LSTMCell`.

I believe this is due to it not using a Tensor for it's state, and instead using a `LSTMStateTuple`.

**Comment by malmaud** [comment]
As well, gradients are not working through `dynamic_rnn` with the RNN cells. I'm working on that.

**Comment by oxinabox** [comment]
Is this still open?

**Comment by malmaud** [comment]
No
