### ISSUE TITLE
Adding unsorted_segment_sum

### ISSUE THREAD

**Issue by pevnak** [malmaud/TensorFlow.jl#184]
Hello all,
I have decided to ditch my nn library in favour of Tensor Flow, as I have found it implements a critical element for me, which is unsorted_segment_sum. Unfortunately this one is not exported by TensorFlow.jl. I have tried to write the export by myself, as 

```
@eval TensorFlow.@op function unsorted_segment_sum(data::AbstractTensor,segment_ids::Array{Int64}; name=nothing)
    if name === nothing
        name = TensorFlow.get_name("unsorted_segment_sum")
    end
    desc = TensorFlow.NodeDescription("unsorted_segment_sum", name)
    TensorFlow.add_input(desc,Tensor(data))
    TensorFlow.add_input(desc,Tensor(segment_ids))
    TensorFlow.add_input(desc,Tensor(length(unique(segment_ids))))
    TensorFlow.add_input(desc,Tensor(name))
    Tensor(Operation(desc), 1)
end
```

but executing the above as
```
a=constant(ones(4,5))
b=constant(randn(4,5))
c=a+b
d=unsorted_segment_sum(c,[1,1,2,2])
```
fails with this error:

```
ERROR: Tensorflow error: Status: Op type not registered 'unsorted_segment_sum' while building NodeDef 'unsorted_segment_sum_3'

 in check_status(::TensorFlow.Status) at /Users/tpevny/.julia/v0.5/TensorFlow/src/core.jl:339
 in TensorFlow.Operation(::TensorFlow.NodeDescription) at /Users/tpevny/.julia/v0.5/TensorFlow/src/core.jl:802
 in #unsorted_segment_sum#5(::Void, ::Function, ::TensorFlow.Tensor, ::Array{Int64,1}) at ./REPL[49]:10
 in unsorted_segment_sum(::TensorFlow.Tensor, ::Array{Int64,1}) at ./REPL[49]:2
```
, which does not surprise me due to lack of my understanding of library internals. May I ask someone to help me with this? This piece of information is critical for my work.

**Comment by JobJob** [comment]
I cannot help directly, but have you seen this recently added doc: https://github.com/malmaud/TensorFlow.jl/blob/master/docs/src/addingops.md

**Comment by oxinabox** [comment]
Why do you have a `@eval` at the start?

Anyway, 
one problem (and the one causing that error) is you have the "true_name" of the operation wrong.
See the instructions @JobJob  linked.

The true name is `"UnsortedSegmentSum"` from
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt#L25705.

**Comment by pevnak** [comment]
Thank you very much for quick answer. My current version looks like this and it seems to work reasonably.

```
@eval TensorFlow.@op function unsorted_segment_sum(data,segment_ids,nbuckets; name=nothing)
    if name === nothing
        name = TensorFlow.get_name("unsorted_segment_sum")
    end
    desc = TensorFlow.NodeDescription("UnsortedSegmentSum", name)
    TensorFlow.add_input(desc,Tensor(data))
    TensorFlow.add_input(desc,Tensor(segment_ids))
    TensorFlow.add_input(desc,Tensor(nbuckets))
    Tensor(Operation(desc), 1)
end
```

**Comment by malmaud** [comment]
A PR would be very welcome, if you get a chance.

**Comment by pevnak** [comment]
Hi Malmaud,
I did PR.

Tomas
