### ISSUE TITLE
Pkg.build("TensorFlow") will replace the manually compiled libtensorflow.so file

### ISSUE THREAD

**Issue by jingpengwu** [malmaud/TensorFlow.jl#191]
I compiled a libtensorflow.so file and put it in the dep/usr/bin/ folder, but whenever I run Pkg.build("TensorFlow"), it will automatically redownload a so file and replace it.

**Comment by malmaud** [comment]
Hmm, hard to know what the right thing to do here is since `Pkg.build` doesn't automatically download a new file if libtensorflow.so is already there, then how would users upgrade libtensorflow.so?

**Comment by jingpengwu** [comment]
that's right. Maybe gettting the path from a custom environment variable is a good choice? the default path of libtensorflow.so could be the one in dep/usr/bin.

**Comment by oxinabox** [comment]
Maybe can use some meta-data on the file that is there to see if it is one that was downloaded via `Pkg.build` or not.
Maybe the hash, or load it and check some verson string. 

Alternatively, `Pkg.build` could prompt the users for instructions if the file was found.
