### ISSUE TITLE
List of what needs to be covered by Tensorflow.jl and what is being covered

### ISSUE THREAD

**Issue by hpoit** [malmaud/TensorFlow.jl#198]
Hello Jon, 

How would you define a list of what needs to be covered by Tensorflow.jl, and what is being covered? 

Cheers, Henry

**Comment by StefanKarpinski** [comment]
Seem like a better discussion for discourse.

**Comment by malmaud** [comment]
Yes, please ping on me on discourse and I'm happy to discuss.
