### ISSUE TITLE
TFRecordWriter and tf_record_iterator

### ISSUE THREAD

**Issue by classner** [malmaud/TensorFlow.jl#205]
Thank you for the great package! I noticed that both, the `TFRecordWriter` and `tf_record_iterator` are currently still unwrapped. They are incredibly useful for creating and reading .tfrecord files. Are you planning to wrap them or are there inherent problems making this impossible?

**Comment by malmaud** [comment]
Just hasn't been a priority. Wouldn't be hard at all.

**Comment by malmaud** [comment]
Also, you're welcome!
