### ISSUE TITLE
kernel dying...

### ISSUE THREAD

**Issue by zahachtah** [malmaud/TensorFlow.jl#21]
I have very little experience with tensor flow but am hoping to make a simple version of the [Karpathy game](http://cs.stanford.edu/people/karpathy/reinforcejs/waterworld.html) eventually. However, Already at first attempt I get stuck with the kernel dying on me at the last line (julia 0.5 rc 3)

```julia
using TensorFlow
using Distributions
situationDim=10
actionDim=10
n_hidden_1=100
n_hidden_2=100


function weight_variable(shape)
    initial = map(Float64, rand(Normal(0, .001), shape...))
    return Variable(initial)
end

function bias_variable(shape)
    initial = fill(Float64(.1), shape...)
    return Variable(initial)
end

session = Session(Graph())

x = placeholder(Float64, shape=[-1, situationDim])
y = placeholder(Float64, shape=[-1, actionDim])
layer1=nn.tanh(x*weight_variable([situationDim, n_hidden_1])+bias_variable(n_hidden_1))
layer2=nn.tanh(layer1*weight_variable([n_hidden_1, n_hidden_2])+bias_variable(n_hidden_2))
y_out=nn.softmax(layer2*weight_variable([n_hidden_2, actionDim])+bias_variable(actionDim))
cross_entropy = -reduce_sum(y.*log(y_out))
train_step = train.minimize(train.AdamOptimizer(1e-4), cross_entropy)
```

Any suggestions would be much appreciated. If I can get some simple reinforcement algorithm working I'd be happy to add it to the examples of TensorFlow.jl

If I may also add, how do you debug tensor flow code? how can I look at how it is linked together and that dimensions are right?

**Comment by malmaud** [comment]
Try checking out the master branch of TensorFlow.jl, `Pkg.checkout("TensorFlow")`

**Comment by zahachtah** [comment]
did that and also build("TensorFlow")

I get:

train_step = train.minimize(train.AdamOptimizer(1e-4), cross_entropy)
F ./tensorflow/core/lib/gtl/inlined_vector.h:155] Check failed: i < size() (0 vs. 0)

signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 10484772 (Pool: 10481619; Big: 3153); GC: 20
Abort trap: 6

Maybe I have some dimensions messed up? Do you by any chance have an example of a simple MLP reinforcement learning example?

**Comment by malmaud** [comment]
Hmm, it works for me. A dimension problem would just raise an error, not crash. What operation system are you on? Are you using the CPU or GPU version? Can you reproduce the issue if you try it again?

**Comment by malmaud** [comment]
Also double-check that you're on the very latest master. A version just a few days old I think would crash on the example you gave.

**Comment by zahachtah** [comment]
I am on:

 - TensorFlow                    0.3.1+             master
OSX10.11.5 using CPU

Reinstalled tensorflow using as described [here](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html)

I get the same error again

Must be some configuration I have since its working for you, not much to do then, I may reinstall everything or try another computer. Thanks for looking into this @malmaud !

Jon

**Comment by malmaud** [comment]
You can try the new branch I'm working on, `Pkg.checkout("TensorFlow", "precompile")`. It uses a slightly different version of the TensorFlow C library that might help.

**Comment by zahachtah** [comment]
\O/

That did the trick, thanks!!!

**Comment by malmaud** [comment]
Great!
