### ISSUE TITLE
Document how to Save and Load a trained network?

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#211]
There is very little in the way of documentation for saving a network to use it again later.

Just an example of using something called a `Saver`.

It is unclear as to if this saves only the network's variable values, or also its structure.
There is no examples for using `restore`

-----------------

What I thought *might* work but clearly does not is:

```julia
....
saver = train.Saver()
save_path = joinpath("models", "1.jld")
train.save(saver, sess, save_path)

sess2 = Session(Graph())
sess2 = train.restore(saver, sess2, save_path)
```

Errors with 

```
Tensorflow error: Status: FeedInputs: unable to find feed output placeholder:0

 in check_status at core.jl:402 [inlined]
 in run(::TensorFlow.Session, ::Array{TensorFlow.Port,1}, ::Array{Any,1}, ::Array{TensorFlow.Port,1}, ::Array{Ptr{Void},1}) at run.jl:100
 in run(::TensorFlow.Session, ::Array{Any,1}, ::Dict{Any,Any}) at run.jl:169
 in restore(::TensorFlow.train.Saver, ::TensorFlow.Session, ::String) at train.jl:259
 in include_string(::String, ::String) at loading.jl:441
 in eval(::Module, ::Any) at boot.jl:234
...
```

Similar even if I make `sess2` hold a graph that is identical in structure to the one being restored from

**Comment by malmaud** [comment]
It is also possible to save both the structure and the variable values, but you are right that it's not documented well. I will do that sometime.

**Comment by oxinabox** [comment]
On reading the [upstream docs](https://www.tensorflow.org/programmers_guide/variables#saving_variables)

I now get it -- at least for saving variable values.
I am recording this for reference of anyone else who comes at this before proper docs are written (including future me). It might also be useful as a starting point for some docs.
`Saver` is a function that adds a node to the network -- using always current graph (AFAICT -- I think this might be a bit of a UX bug ).
This node is used for both saving (when triggered by `train.save`), and restoring (when triggered by `train.restore`).

Lets say I have some function `define_network` which defines some neural network, and returns it.
and a function `train_network!` which runs the training.

Then the following workflow to setup and save my network: (this part works)

```julia
save_path = joinpath("...", "models", "1.jld")

graph1 = define_network(...)
sess1 = Session(graph1)
train_network!(...)
saver = train.Saver()
train.save(saver, sess, save_path)
```

The **Incorrect** way to restore it would be: (and the mistake I was making was)

```julia
graph2 = define_network(...) #Get a nother network of the same shape
sess2 = Session(graph1)
train.restore(saver, sess2, save_path)
```

This errors with `Tensorflow error: Status: FeedInputs: unable to find feed output placeholder:0`
This is because the node `saver` is not part of the graph in `sess2`

What will work is creating a *new* `Saver` node for the new network, to be used to restore variable values into it.

```julia
graph2 = define_network(...) #Get a nother network of the same shape
sess2 = Session(graph1)
saver2 = train.Saver()
train.restore(saver2, sess2, save_path)
```
