### ISSUE TITLE
Extending the `gradients` function

### ISSUE THREAD

**Issue by MikeInnes** [malmaud/TensorFlow.jl#212]
The `gradients` function currently supports neither multiple `y` values nor providing the gradients of those values.

It hopefully shouldn't be too hard to add this, I think it's just a case of forwarding those arguments correctly to the Python side (but please correct me if I'm wrong there).

**Comment by oxinabox** [comment]
Can you clarify what you mean by "providing the gradients of those values" ? 
Do you mean providing some gradients as inputs to the function?

**Comment by MikeInnes** [comment]
Yes, in any case where the computation produces more than a single scalar output, `gradients` needs to know the gradients of those outputs to produce a meaningful result.

```julia
julia> X = Variable([1,2,3])
TensorFlow.Variable(<Operation 'node_3'>, <Operation 'node_3/Assign'>)

julia> Y = Variable([4,5,6])
TensorFlow.Variable(<Operation 'node_4'>, <Operation 'node_4/Assign'>)

julia> Z = X+Y
<Tensor add_2:1 shape=(3) dtype=Int64>

julia> run(sess, global_variables_initializer())

julia> run(sess, gradients(Z, [X, Y]))
2-element Array{Array{Int64,1},1}:
 [1, 1, 1]
 [1, 1, 1]
```

This produces a result, but the gradients default to arrays of `1`s.

**Comment by oxinabox** [comment]
I'll take a poke at this soonish, maybe sometime this week.
You are right that it should be pretty simple.

I think I want it anyway for some of the DiffEq stuff I am talking to @ChrisRackauckas about.
