### ISSUE TITLE
Trouble installing on 0.6

### ISSUE THREAD

**Issue by bkalpert** [malmaud/TensorFlow.jl#214]
After a seemingly successful Pkg.add("TensorFlow") on Mac OS X 10.10.5, I have trouble using:

> $ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-rc1.0 (2017-05-07 00:00 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin14.5.0

> julia> using TensorFlow
INFO: Precompiling module TensorFlow.
ERROR: LoadError: LoadError: LoadError: AssertionError: item.head == Symbol("=>")
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:552
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:552
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:552
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Users/alpert/.julia/v0.6/TensorFlow/src/ops/nn.jl, in expression starting on line 139
while loading /Users/alpert/.julia/v0.6/TensorFlow/src/ops.jl, in expression starting on line 158
while loading /Users/alpert/.julia/v0.6/TensorFlow/src/TensorFlow.jl, in expression starting on line 171
ERROR: Failed to precompile TensorFlow to /Users/alpert/.julia/lib/v0.6/TensorFlow.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:686
 [2] _require(::Symbol) at ./loading.jl:473
 [3] require(::Symbol) at ./loading.jl:386

A similar error occurred under CentOS 7.  I have not installed the package on earlier versions of Julia, so this problem may be unrelated to the current version.  Any clues?

**Comment by merl-dev** [comment]
try `Pkg.checkout("TensorFlow")`

**Comment by bkalpert** [comment]
Thanks very much!

**Comment by merl-dev** [comment]
don't thank me yet...working through quite a few test errors :(

**Comment by malmaud** [comment]
I think everything should be working at this point. Please comment if you're still having trouble.
