### ISSUE TITLE
Feature request: Wrap op tf.svd

### ISSUE THREAD

**Issue by alha02** [malmaud/TensorFlow.jl#218]

**Comment by oxinabox** [comment]
Are you in any kinda rush? This will be done when #216 is done.

Doing it by hand is easy enough though.
See https://github.com/malmaud/TensorFlow.jl/blob/master/docs/src/addingops.md

**Comment by alha02** [comment]
Oh, sorry I didn't realize that this was in the pipeline.

**Comment by oxinabox** [comment]
Reopening this, because it wasn't quiet closed by #216.

svd is there in the Ops submodule,
but it needs a bit of turning around to be made to overload `Base.svd`.
Just reordering the returned outputs, I think

**Comment by malmaud** [comment]
Closed in https://github.com/malmaud/TensorFlow.jl/commit/12e71f018d8ec8b43afed3cf9f214d4c9ad6069b.
