### ISSUE TITLE
Enable precompilation

### ISSUE THREAD

**Issue by malmaud** [malmaud/TensorFlow.jl#22]

**Comment by moon6pence** [comment]
+1 for this issue. 

By the way, is there any point to be considered to support precompiliation? 
I just run `Pkg.compilecache("TensorFlow")` but there were error while loading the package.

**Comment by malmaud** [comment]
Yes, there are some issues with global variables and globally loading shared libraries that I'm working out.

**Comment by malmaud** [comment]
Resolved on master

**Comment by moon6pence** [comment]
Thanks! I would like to test it immediately.

**Comment by moon6pence** [comment]
Much better but not enough. Maybe due to recompiling google module from ProtoBuf.jl? 

I added :+1:  to issue you wrote to ProtoBuf.jl github.

**Comment by malmaud** [comment]
The reason I think it's still slow to load is it spins up a separate Julia process to handle interaction with the Python code necessary for computing gradients. I'm investigating how to remove the need for the second process.

**Comment by malmaud** [comment]
Done. Should be much faster to load now.
