### ISSUE TITLE
Build TensorFlow from source

### ISSUE THREAD

**Issue by aterenin** [malmaud/TensorFlow.jl#220]
Hi,

For maximum performance, it is highly recommended to build TensorFlow from source. This will also be needed for Mac OS X GPU support, as Google said they will not be releasing a binary going forward.

I suggest adding such an option. I suggest using Homebrew.jl on OS X - there is already a formula for installing TensorFlow available at https://github.com/Homebrew/homebrew-core/blob/f7108950af85e222b11523c7ae67140736faa062/Formula/libtensorflow.rb that will probably need minor edits for GPU support. I am not familiar with how Julia handles dependencies on Linux, but perhaps somebody else is.

Thanks for looking.

**Comment by oxinabox** [comment]
There are instructions in the docs for building tensorflow from source.
There is also a script in `/deps` to do it.
The `/deps` script could I guess be set to run automatically based on an enviroment variable.

I actually can't get that script to run,
but I am not very familiar with docker.

**Comment by aterenin** [comment]
Thanks, just saw that script. I believe that is for Linux versions only. 

Building via Docker may also result in performance loss, albeit a much smaller one compared to downloaded binaries. Assuming Docker doesn't do anything unexpected, it should compile with SSE instructions, correct CUDA compute capability, etc, but may not link to Intel MKL, etc, if the user has them installed. This would make it far better than precompiled binaries, but not as good as building without Docker. On the other hand, Docker makes managing dependencies easier, so it may be the simpler solution - I am not familiar with how Julia handles this on Linux.

Since this is already implemented on Linux, perhaps we only need to consider Mac OS X. With Homebrew.jl it should be straightforward - just download the correct version of the formula and run `brew install --build-from-source libtensorflow`. It would definitely be helpful to have a environment variable for running that script automatically.

**Comment by aterenin** [comment]
A quick update. Adding the following to the libtensorflow.rb formula results in a successful GPU build on my system.


    url "https://github.com/tensorflow/tensorflow/archive/v1.0.0-rc1.tar.gz"
    sha256 "55d657e5f9d3a3630e616d6928ff648172c803004541066105beef3b7d685207"

and

    ENV["TF_NEED_CUDA"] = "1"
    ENV["GCC_HOST_COMPILER_PATH"] = "/usr/bin/gcc"
    ENV["TF_CUDA_VERSION"] = "8.0"
    ENV["CUDA_TOOLKIT_PATH"] = "/usr/local/cuda/"
    ENV["TF_CUDNN_VERSION"] = "5"
    ENV["CUDNN_INSTALL_PATH"] = "/usr/local/cuda/"
    ENV["TF_CUDA_COMPUTE_CAPABILITIES"] = "6.0"

as well as

`  system "bazel", "build", "--compilation_mode=opt", "--copt=-march=native", "--config=cuda", "tensorflow:libtensorflow.so"`

and running

  Homebrew.brew(`install --build-from-source libtensorflow`)

yields an (almost) fully functional libtensorflow. It successfully executes graphs on the GPU (I checked this by timing a large matrix multiply), however, the function

` tf.gradients `

is broken. This is presumably due to use of Python. Is anyone familiar enough with Python to help debug this?

**Comment by malmaud** [comment]
The Python default TensorFlow installation via `pip` doesn't build from source - I view `Pkg.add("TensorFlow")` as the Julia equivalent. An advanced user who wants to build from source can consult the TensorFlow.jl README on how to install a custom libtensorflow.(so/dylib).

Trying to automatically build from source with `Pkg.add` sounds like a nightmare to get working across different environments.

**Comment by aterenin** [comment]
It's true that pip will download a binary - in fact, it's one of the reasons people sometimes describe TensorFlow as slow. The MXNet package for Julia will build from source, so I would encourage considering adding an option to this package.

Something as simple as using Homebrew.jl to build TensorFlow if the user switches an appropriate environment variable on and creating a symlink seems sufficient.

In any event, documentation should be updated to indicate that we are using a 1.1.0 binary and not 1.0.0/1.0.1. I don't see anything in the documentation on building from source, if you like I could write up my instructions and make a PR because on OS X the process is straightforward once you know what version you need.

**Comment by malmaud** [comment]
It's here in the README https://github.com/malmaud/TensorFlow.jl#optional-using-a-custom-tensorflow-binary.

Also, the vast majority of people doing serious work with TensorFlow are doing it on the GPU -- the CPU speedups you get from compiling aren't really relevant.

**Comment by aterenin** [comment]
Thanks, didn't realize those instructions were there.

The same performance situation applies to GPU - compile with old CUDA compute capability and performance will go down, I believe Google builds with 3.5 and 5.5 by default. But this is a more minor issue. 

In any event, I understand not wanting to deal with platform issues. It would be helpful if the readme lists the version of TensorFlow binary needed as TensorFlow.tf_version() is not accurate. This way users are not trying to compile the wrong version.

**Comment by malmaud** [comment]
I'll close this for now since automatically building from the source isn't on my personal roadmap (although a PR would be fine). https://github.com/malmaud/TensorFlow.jl/issues/229 remains an issue.
