### ISSUE TITLE
TPU support

### ISSUE THREAD

**Issue by PallHaraldsson** [malmaud/TensorFlow.jl#222]
This is kind of a question; maybe nothing has to be done.

Google has made "tensor processing units" (TPUs) for accelerating TensorFlow. Am I to assume Julia will "just work" with them (no less than say Python's wrapper)?

Note: Their [just released second generation] TPUs, are only "available" to be rented, similar to Amazon's "cloud" service.

A. I suppose your Julia (and Python) wrapper[s] will "just work", as the potential issues are in the C/C++ code of actual TensorFlow (and/or drivers); however, do you know if all the code would have to run in the cloud or some locally and just the accelerator in Google's cloud?

B. I'm a little curious what the TPUs do (and TensoFlow).., in case you know. I think they just accelerate linear algebra )similar to GPUs, just dropping graphics-specific stuff such as texture-mapping features) and specifically tensors (I'm not to familiar with them.. believe "just" [multi-]LA?).'

C. I'm also guessing, the TPUs may be a reason to favor using TensorFlow over all other frameworks/wrappers..?

**Comment by oxinabox** [comment]
I've not heard much of these so just speculating.

A. I believe so, problem for the C/C++ backend. Running all things on the cloud would make sense. Unless you have 1G internet, not having all your code running in the same data center would be a waste of time from the communication overhead.

B. Yes. I don't know for sure, but I imaging very similar to a Xeon Phi. which is in turn very similar to a GPGPU (eg a Tesla) which is similar to a normal GPU.

C. Maybe. But there are other concerns when choosing a tool.

**Comment by malmaud** [comment]
Yes, TensorFlow.jl just calls out to the underlying TensorFlow C library, which in turn controls what device actually perform the computation. So it should just work.
