### ISSUE TITLE
Most RNNs are broken on master

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#225]
They broke with #209.
Which changes `cat` to match julia's behavour of expanding dims.
Which I wouldn't have thought would break anything, but did.

I have a fix.
Change `cat` in the RNNs to `concat` which only does the Tensorflow stuff.

I want to wait til I have a better understanding of why this is happening
and to have maybe some more tests written,
before I make the PR

**Comment by malmaud** [comment]
I already fixed it on my branch, which is actually ready to go now.

**Comment by oxinabox** [comment]
When looking into this I got a bit side-tracked.
And I am now most of the way to removing the requirement for a statically known batch_size for dynamic RNNs.
(which I think is a feature Python tensorflow does not have.)

**Comment by malmaud** [comment]
Fixed now
