### ISSUE TITLE
Eltype is defined on values, rather than types

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#226]
It is muchly preferred for eltype to be defined on types.

Right now in many places it is defined on values.

eg:

```julia
Base.eltype(l::LSTMStateTuple) = eltype(l.c)
```

Rather than

```julia
Base.eltype{C}(::Type{LSTMStateTuple{C}}) = eltype(C)
```

Though this don't really matter as you can't act element-wise on Tensors anyway.
And Eltype being all trait-y is all about optimisings looping in julia

**Comment by malmaud** [comment]
Closed in https://github.com/malmaud/TensorFlow.jl/pull/242
