### ISSUE TITLE
ERROR: could not load library "TensorFlow/.../libtensorflow"

### ISSUE THREAD

**Issue by wucutin** [malmaud/TensorFlow.jl#270]
when I add , build, using TensorFlow, all is OK
But,  when I follow the TensorFlow.jl Documentation, and set "sess = TensorFlow.Session()",  REPL throw error:
ERROR: could not load library "/home/liu/.julia/v0.5/TensorFlow/src/../deps/usr/bin/libtensorflow"
libcudnn.so.5: cannot open shared object file: No such file or directory
 in dlopen(::String, ::UInt32) at ./libdl.jl:90
 in tf_version() at /home/liu/.julia/v0.5/TensorFlow/src/core.jl:21
 in upgrade_check(::VersionNumber) at /home/liu/.julia/v0.5/TensorFlow/src/core.jl:416
 in get_def_graph() at /home/liu/.julia/v0.5/TensorFlow/src/core.jl:432
 in (::TensorFlow.##call#40#42)(::Void, ::Bool, ::Type{T}) at /home/liu/.julia/v0.5/TensorFlow/src/core.jl:516
 in TensorFlow.Session() at /home/liu/.julia/v0.5/TensorFlow/src/core.jl:510

Thanks for your help!
#-----------------------------------------
versioninfo()
Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
#-------------------------------------------

**Comment by malmaud** [comment]
If you downloaded the GPU version, you need cudnn to use it. Did you? What version of TensorFlow.jl are you using?

**Comment by wucutin** [comment]
@malmaud  yes,  I also had installed CUDA previously, the version of TF is 0.6.4. Besides, Pkg.test("TensorFlow") is passed.

**Comment by malmaud** [comment]
Mmm, all I can say is to make sure that cudnn version 5 is in your `LD_LIBRARY_PATH`.

**Comment by wucutin** [comment]
@malmaud  Thank you very much
