### ISSUE TITLE
reshape also reorders the data in memory?

### ISSUE THREAD

**Issue by jeff-regier** [malmaud/TensorFlow.jl#275]
In the code below, calling `reshape` appears to change the order of the array in memory. I suspect this has something to do with row-based/column-based indexing. Seems like a problem.

```
julia> run(session, t)[:]
9-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

julia> run(session, reshape(t, [3, 3]))[:]
9-element Array{Int64,1}:
 1
 4
 7
 2
 5
 8
 3
 6
 9
```

**Comment by malmaud** [comment]
Mmm, can you give a fuller example of where it would be a problem?

**Comment by malmaud** [comment]
I'm going to close due to a lack of response.

**Comment by oxinabox** [comment]
Are you sure this should be closed?
It documents a real thing that does occur.
I've tried a few times to workout when it would matter in a practical scenario, but I'm not a computer vision guy, and I suspect the answers are computer vision related.

**Comment by malmaud** [comment]
It does occur, but I'm not sure I see the issue per se. It's ambiguous what it means to reshape a 2d array into a 1d array. Julia's reshape function chooses one convention, TensorFlow's reshape chooses another.
