### ISSUE TITLE
Visualize() does not work

### ISSUE THREAD

**Issue by jw3126** [malmaud/TensorFlow.jl#279]
Visualization does not work if tensorboard exists but is not in the system path. See [here](https://discourse.julialang.org/t/tensorflow-jl-how-to-use-visualize/5017/2).

**Comment by oxinabox** [comment]
I feel like there is little we can do about this.
We can't exactly know what we don't know.
@malmaud  is the plan to document this in the docstring (with instructions on modifying the path) and move on?

**Comment by malmaud** [comment]
Indeed, let's just check first if it's in Conda's bindir, then if it's in the system path, then give a helpful error message.
