### ISSUE TITLE
Very unusual behavour regarding static loops and scalar placeholders

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#285]
Ok, this is really weird.
I have narrowed it down from something complex that involved generating a deepnet with dropout.

This bug seems to occur, if one is both multiplying a matrix tensor with a scalar placeholder **and** displaying the value of that tensor, in a loop.
(Not 100% sure loop is required)

Edit: 
there is a mistake in one of the examples. Posted here.
To avoid confusion I have posted a new clearer example below

These are weird happenings,
so it is quiet likely a mistake on my part, but I can't see it.

**Comment by oxinabox** [comment]
MWE:

```
sess = Session(Graph())
X = placeholder(Float32, shape=[-1, 100])
KeepProb = placeholder(Float32, shape=[])
Zs = [X]
for ii in 1:3
    println(ii)
    @show get_shape(KeepProb)
    @show Zs[end] #LINE A
    @show get_shape(KeepProb)
    #Zii = Zs[end] #LINE B1
    Zii = Zs[end].*KeepProb #LINE B2
    push!(Zs, Zii)
end

---
OUTPUT:
---
get_shape(KeepProb) = TensorShape[]
Zs[end] = <Tensor placeholder:1 shape=(?, 100) dtype=Float32>
get_shape(KeepProb) = TensorShape[]
2
get_shape(KeepProb) = TensorShape[]
Zs[end] = <Tensor Mul:1 shape=(?, 100) dtype=Float32>
get_shape(KeepProb) = TensorShape[1, 1]
3
get_shape(KeepProb) = TensorShape[1, 1]
Zs[end] = <Tensor Mul_2:1 shape=(?, 100) dtype=Float32>
get_shape(KeepProb) = TensorShape[1, 1]
```


But if you comment out **LineA** or switch **LineB2** for **LineB1**
then everthing is fine:

```
Output:
---
1
get_shape(KeepProb) = TensorShape[]
Zs[end] = <Tensor placeholder:1 shape=(?, 100) dtype=Float32>
get_shape(KeepProb) = TensorShape[]
2
get_shape(KeepProb) = TensorShape[]
Zs[end] = <Tensor placeholder:1 shape=(?, 100) dtype=Float32>
get_shape(KeepProb) = TensorShape[]
3
get_shape(KeepProb) = TensorShape[]
Zs[end] = <Tensor placeholder:1 shape=(?, 100) dtype=Float32>
get_shape(KeepProb) = TensorShape[]
```

**Comment by oxinabox** [comment]
Ok, worked it out.
That was annoying.

In the medium-long term maybe we should make 
TensorShape.dims a `tuple`,
Which would actually be very similar/equivalent to https://github.com/malmaud/TensorFlow.jl/issues/183

**Comment by malmaud** [comment]
Ah great, thanks for tracking that down
