### ISSUE TITLE
Pkg.build() issue for GPU

### ISSUE THREAD

**Issue by abieler** [malmaud/TensorFlow.jl#292]
I get the following error when doing `Pkg.build()` in Julia v0.6.

```julia
PackageNotFoundError: Package missing in current linux-64 channels:                                    
  - tensorflow-gpu 1.2.0*
```

Is this a coda issue?

**Comment by malmaud** [comment]
Seems like it. @oxinabox would probably know more than I would.

**Comment by oxinabox** [comment]
Yes, it is.
tensorflow-gpu is slower to update what is available, because it is only on the Anaconda channel,
not the conda-forge channel.

One-day maybe  conda-forge will include the GPU version  (see https://github.com/conda-forge/tensorflow-feedstock/issues/10).


However, my goal with using Conda to add tensorflow-gpu, was that it was supposed to install the CUDA and CUDNN repos as well.
But on testing it, I found that while it tried, it kinda messed them up and I hand to install them manually anyway.

We don't actually need the GPU-enabled Python code, to work with the GPU-enabled backend.
So we could depend solely on the normal python tensorflow.

**Comment by abieler** [comment]
Not sure where exactly to go from here :)

I have a working Python install of TF. Can I somehow point TensorFlow.jl to use this?
(Similar to the manual compilation option for MXNet.jl by setting an env variable or so? http://dmlc.ml/MXNet.jl/latest/user-guide/install/#Installation-Guide-1)

**Comment by oxinabox** [comment]
You can, by chaning the Enviroment Variable PYTHON.
See pycall docs, 
https://github.com/JuliaPy/PyCall.jl

I'll push a fix to our build script shortly.

**Comment by abieler** [comment]
Great!

The following ran successfully:

```julia
ENV["PYTHON"] = "/usr/bin/python"
Pkg.build("PyCall")
ENV["TF_USE_GPU"] = "1"
Pkg.build("TensorFlow")
``` 

But then I get an error for:

```julia
a = constant(10)

ERROR: could not load library "/home/abieler/.julia/v0.6/TensorFlow/src/../deps/usr/bin/libtensorflow"
libcudnn.so.5: cannot open shared object file: No such file or directory
```

**Comment by oxinabox** [comment]
You need to install cudnn.
And make sure it is in your LD_LIBRARY_PATH

**Comment by abieler** [comment]
Yes I had installed cudnn and it was added it to LD_LIBRARY_PATH.
Turns out there was libcudnn.so.**6** instead of libcudnn.so.**5**.

Creating a the softlink below solved the problem:
```
sudo ln -s libcudnn.so.6.* libcudnn.so.5
```

Thanks for the help!

**Comment by malmaud** [comment]
If upstream TensorFlow has bumped up to to libcudnn 6 and we are still
shipping a binary linking against 5, we should probably fix that on our end.

**Comment by oxinabox** [comment]
CuDNN 5.1 is still preferred:
https://www.tensorflow.org/versions/r0.12/get_started/os_setup#requirements

> The GPU version works best with Cuda Toolkit 8.0 and cuDNN v5.1.

**Comment by malmaud** [comment]
Ah OK, let's keep the status quo then.

**Comment by abieler** [comment]
From what I read they'll switch to cudnn 6 for tensorflow version 1.3

**Comment by amellnik** [comment]
Should this be revisited now that 1.4 is out?  `TensorFlow.jl` still expects cuDNN 5.

**Comment by oxinabox** [comment]
> Should this be revisited now that 1.4 is out? TensorFlow.jl still expects cuDNN 5.

Not sure what part you mean to suggest revisititing.
This issue strayed off-course, from the original issue being about Conda.
You should probably open another issue.

TensorFlow.jl still expects cuDNN 5, because we still ship with TensorFlow 1.2.0
