### ISSUE TITLE
 consumers of an operation

### ISSUE THREAD

**Issue by pevnak** [malmaud/TensorFlow.jl#294]
Hi All,
I would like to implement this method [ SGD with Coupled Adaptive Batch Size (CABS)
](https://arxiv.org/abs/1612.05086) which should automatically determine the size of the minibatch on basis of the variance of the estimate of the gradient. I am curious about it, because in security applications the signal to detect is typically very weak and I expect to need a large minibatch to move in the right direction. So far, I have this only experimentally justified and I would be curious, how these method will perform. The problem is that estimating variance is expensive and CABS suggest a method, which does it efficiently. The crucial part is implemented here
[github.com/ProbabilisticNumerics/cabs/blob/master/gradient_moment.py](github.com/ProbabilisticNumerics/cabs/blob/master/gradient_moment.py).
It seems to me  they need to identify consumers of a tensor (line 79 of gradient_moment.py).
I wonder if it is possible to do so in TensorFlow.jl?
Thanks for help.
Tomas

**Comment by malmaud** [comment]
You can call `TensorFlow.get_def` on a tensor to get back a datastructure with the names of the tensors it depends on. We could probably have an API to make it more simpler.

**Comment by pevnak** [comment]
Thanks Jon,
I will try to look at that and dig this out.
I apologise for cross posts.
Best wishes,
Tomas

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by pevnak** [comment]
Interesting. It seems like it might work, though it will be tedious. If I implement the consumer operation, I will post it back.
