### ISSUE TITLE
Make LSTM forget-bias easier to specify

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#299]
It is apparently super important to set your forget bias to 1.0 or greater.
See e.g.  [Jozefowicz et al, 2015, "An Empirical Exploration of Recurrent Network Architectures"](http://proceedings.mlr.press/v37/jozefowicz15.pdf?utm_campaign=Revue%20newsletter&utm_medium=Newsletter&utm_source=revue).

[Right now, we initialize it to be 0.](https://github.com/malmaud/TensorFlow.jl/blob/4c729522d54bdbb87bc0fcc27ec870ffcc7f32a4/src/ops/rnn_cell.jl#L155)

Python's [BasicLSTMcell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell) takes it as a parameter, with default value 1.0.
So does it's regular [LSTMcell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/LSTMCell).

We should do this also.
I think the change is easy to make.
I can do so if you think it is a good idea.

**Comment by malmaud** [comment]
Yes, please do so. Great catch.
