### ISSUE TITLE
get_input seg faults after variable init

### ISSUE THREAD

**Issue by zenna** [malmaud/TensorFlow.jl#305]
Variable initialization with `tf.run(sess, tf.global_variables_initializer())` creates a new `op` called `Group` with type `NoOp`.
The graph indicates this op takes 1 input but asking for its inputs using `get_input` causes a segfault.

```julia
import TensorFlow
const tf = TensorFlow
sess = tf.Session()

y = tf.Variable(Float64[3,4], name="y")

tf.run(sess, tf.global_variables_initializer())

ops = collect(tf.get_operations())
groupop = ops[end]
tf.get_input(groupop, 1)
```

**Comment by oxinabox** [comment]
You arecorrect, this does occur.
But what are you trying to do?

`get_input` is a private (unexported) internal method.
Its not for normal use.

**Comment by malmaud** [comment]
Where are you seeing that op takes an input? It doesn't - it just has control inputs, which `get_input` won't return.
