### ISSUE TITLE
Pkg.build("TensorFlow") depends on unzip on linux

### ISSUE THREAD

**Issue by jpfairbanks** [malmaud/TensorFlow.jl#307]
While installing TensorFlow.jl on an HPC cluster, I found that the compute nodes don't have unzip installed on them. So Pkg.build("TensorFlow") fails. This is probably not a big deal for desktop and cloud users who have root on their boxes and unzip installed.

This could be handled by:

- installing unzip on the compute nodes (requires admin privileges)
- finding another way to unzip the files and checking if they are preinflated
- or using GZip.jl to inflate them.

**Comment by oxinabox** [comment]
This is true.
It is also a problem for a future windows version install,
and unzipping from the command-line in windows is awful
[See here](https://github.com/malmaud/TensorFlow.jl/blob/b4a8474b5d047e6c60a9c501d8034c224455799c/deps/build.jl#L119)

Once https://github.com/tensorflow/tensorflow/issues/8669
is fixed upstream,
we can stop distributing our own binaries, and use the official ones.

This will mean Linux and Mac will get tarballs,
and windows will get zipfiles.

Until that point I feel it isn't pressing to mess around with the build script to handle this case.

---

Is this blocking for you?
Or have you deployed one of your workarounds:
 - getting your cluster administrator to install `unzip` -- honestly they really should, it is generally useful
 - writing own unzip program in julia using GZip.jl

**Comment by jpfairbanks** [comment]
Yeah I already requested unzip. A bigger question that expands beyond TensorFlow: Is there any value in running Pkg.build on the compute nodes rather than the head node of a cluster? The head node has nvcc but no GPUs, and the compute nodes have nvcc and GPUs but no unzip.

**Comment by malmaud** [comment]
Is it hard to get GZip.jl working for us? If it's really easy, then we might as do it.

**Comment by oxinabox** [comment]
>Is there any value in running Pkg.build on the compute nodes rather than the head node of a cluster?

No there is no value, `Pkg.build`  does not  do any compiling.
It just downloads things from various locations.

You can locally build some of those things (libtensorflow.so) manually, in order to get better performance. (But beware the need for the custom patch mentioned before).
In those cases I think you should still be able to build on the  head-node, but I'm not 100% sure

**Comment by jpfairbanks** [comment]
Something like

```julia
function readwrite(src::IO, dst::IO)
  fh = src
  buffsize = 32*1024
  buffer = zeros(UInt8, buffsize)
  bytes = 1
  nb = 0
  while bytes > 0
    bytes = readbytes!(src, buffer)
    write(dst, buffer[1:bytes])
    nb += bytes
  end
  return nb
end

function unzip(src::String, dst::String)
  sfh = GZip.open(src, "r")
  dfh = open(dst, "w")
  readwrite(sfh, dfh)
  close(dfh)
  close(sfh)
end
```

might work? It might be useful to put it in GZip.jl

**Comment by malmaud** [comment]
We now use the upstream TensorFlow binaries, which are distributed as `.tar.gz` files.
