### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by Zumbalamambo** [malmaud/TensorFlow.jl#316]
Is it possible to create a standalone python wrapper around libtensorflow so i dont have to install tensorflow from pip everytime?

**Comment by malmaud** [comment]
You can use PyCall directly with the Python TensorFlow. This package is a wrapper over the C TensorFlow API though.

**Comment by Zumbalamambo** [comment]
@malmaud can you please tell me how I can use pycall to use tensorflow as a standalone package?

**Comment by malmaud** [comment]
General questions like that should go to the Julia forum, discourse.julialang.org
