### ISSUE TITLE
comment block not correctly shown

### ISSUE THREAD

**Issue by shencebebetterme** [malmaud/TensorFlow.jl#318]
in src/ops/imported_ops.jl, line 7416
```
output = [b'hir', b'ee', b'n"]
```
here `b'n"` should be replaced by `b'n'`, the intrusion of `"` corrupts comment block structure, and the codes below are shown in comment style, although this causes no error  :)

**Comment by oxinabox** [comment]
Those are not even our docs.
Those are the python docs we are automatically importing.
And that is a python example.

Anyway, I've made an upstream PR for the trivial fix.
Once that is merged and a new TensorFlow release is tagged,
we will regenerate `src/ops/imported_ops.jl`, and it will be fixed.

There is nothing actionable left to do. (All actions can be done in the upstream PR, or will occur automatically).
So I am closing this now.
