### ISSUE TITLE
libtensorflow could not be found [Windows - CPU]

### ISSUE THREAD

**Issue by jmbyars** [malmaud/TensorFlow.jl#323]
![tensorflow_issue](https://user-images.githubusercontent.com/9964645/30875219-ca60de4a-a2c0-11e7-9817-9286edb487e0.png)

Pretty sure there is something I am missing, but I didn't see much in the documentation. Nor did I see the folder that was referenced in the error. TensorFlow is working on Python (not Conda).

Any recommendations on how to remedy this issue?

**Comment by malmaud** [comment]
Unfortunately Windows isn't supported at the moment.
