### ISSUE TITLE
`mnist_full.jl` example broken on TensorFlow master branch

### ISSUE THREAD

**Issue by Evizero** [malmaud/TensorFlow.jl#326]
While it works fine on the tagged version, this is the output i see on the current master branch (for julia 0.6) when running the example script

```
...
INFO: step 1, training accuracy 0.0
INFO: step 101, training accuracy 0.0
INFO: test accuracy 0.0
...
```

**Comment by oxinabox** [comment]
see #352.
(same issue more details)
