### ISSUE TITLE
SELU activation function

### ISSUE THREAD

**Issue by trappmartin** [malmaud/TensorFlow.jl#335]
Hi there,

would it be possible to integrate the selu implementation of Tensorflow in TensorFlow.jl?

See: https://www.tensorflow.org/versions/master/api_docs/python/tf/nn/selu
and the code by Günter: https://github.com/bioinf-jku/SNNs/blob/master/SelfNormalizingNetworks_MLP_MNIST.ipynb

Thanks!
Martin

**Comment by oxinabox** [comment]
It is very possible.
The implementation is trivial.

It is vaguly annoying that it wasn't done on the libtensorflow.so backend.

**Comment by trappmartin** [comment]
Thanks for the fast reply.
Günter uses an implementation of tf.where which is different to the version accessible in TensorFlow.jl.
Do you see a way to implement SELU non-linearities with the where function implemented in TensorFlow.jl?

**Comment by oxinabox** [comment]
https://stackoverflow.com/q/46786317/179081

(I've answered this in chat before, so I wanted to create a canonical post somewhere people can read easily)

**Comment by trappmartin** [comment]
thx
