### ISSUE TITLE
ERROR: LoadError: LoadError: syntax: "()" is not a valid function argument name

### ISSUE THREAD

**Issue by lawanfalalu** [malmaud/TensorFlow.jl#339]
INFO: Precompiling module TensorFlow.
WARNING: Loading a new version of TensorFlow.jl for the first time. This initial load can take around 5 minutes as code is precompiled; subsequent usage will only take a few seconds.
ERROR: LoadError: LoadError: syntax: "()" is not a valid function argument name
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /home/spg/.julia/v0.6/TensorFlow/src/ops.jl, in expression starting on line 119
while loading /home/spg/.julia/v0.6/TensorFlow/src/TensorFlow.jl, in expression starting on line 184
ERROR: Failed to precompile TensorFlow to /home/spg/.julia/lib/v0.6/TensorFlow.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398

When I typed 'julia> using TensorFlow' I get the above message. I am using Ubuntu 14

**Comment by malmaud** [comment]
Should be fixed now with a `Pkg.update()`

**Comment by lawanfalalu** [comment]
Thank you very good
-F

**Comment by lawanfalalu** [comment]
The issue  #339 fixed with Pkg.update(). Thank you Sir. malmaud
