### ISSUE TITLE
stop_gradient

### ISSUE THREAD

**Issue by kevin-w-li** [malmaud/TensorFlow.jl#346]
I'd very much like to see [`stop_gradient` ](https://www.tensorflow.org/api_docs/python/tf/stop_gradient) ported into this API soon! Does anyone have any idea how to achieve this using the current API??

**Comment by oxinabox** [comment]
When raising issues, please include enough information that  I do not have to google for what you are talking about.
TensorFlow has thousands of functions, please link, eg, to the python (or better C++) docs when mentioning them.


You are inluck,
running:

`@tfimport StopGradient`
should create the `stop_gradient` function for you.

I've not tested but this should just work.

**Comment by kevin-w-li** [comment]
Thank you so much! I did not realise there is such an import function, is there documentation for this kind of hidden functions?

**Comment by oxinabox** [comment]
ummm, no I don't think so.
There should be doc strings.
But actually `@tfimport` doesn't have them either.

**Comment by kevin-w-li** [comment]
A slight problem is that this imported function returns unknown shape when the shape of input tensor is known
```
w1 = Variable(randn(3))
@show w1
w2 = stop_gradient(w1)
@show w1
```
output is 
```
w1 = TensorFlow.Variables.Variable{Float64}(<Tensor node_3:1 shape=(3) dtype=Float64>, <Tensor node_3/Assign:1 shape=unknown dtype=Float64>)
w2 = <Tensor StopGradient_2:1 shape=unknown dtype=Float64>
```
Actually the types are also different... This is not the case for the Python API. Can anyone explain the difference of `assign_node` and `var_node`?
