### ISSUE TITLE
Bump utilized TensorFlow version

### ISSUE THREAD

**Issue by Evizero** [malmaud/TensorFlow.jl#349]
Currently it's two minor versions behind and does not support CUDNN 6

**Comment by oxinabox** [comment]
After #338 hopefully we not need a custom binary, and can just download any from the website.
Right now you can just download one from the website and it will only break if you try to use dynamic_rnns

**Comment by bjarthur** [comment]
three minor versions behind now.  hoping i can get something to work with cuda 9 so i don't have to downgrade...

**Comment by malmaud** [comment]
Done
