### ISSUE TITLE
Link to docs in readme not visible

### ISSUE THREAD

**Issue by baggepinnen** [malmaud/TensorFlow.jl#357]
Title says it all, the documentation link is invisible in the README

**Comment by malmaud** [comment]
I don't understand - they seem visible to me?

**Comment by Evizero** [comment]
also visible to me

**Comment by baggepinnen** [comment]
Strange, now it's visible here as well, maybe the server hosting
https://img.shields.io/badge/docs-latest-blue.svg
was down.
