### ISSUE TITLE
Julia test reports custom tensorflow not compiled for AVX2, FMA

### ISSUE THREAD

**Issue by colbec** [malmaud/TensorFlow.jl#400]
On openSUSE Leap 15, with Julia 0.6.3 official release I am trying to get a custom tensorflow working.
Specifically I am following the instructions in the help file to compile with bazel to incorporate AVX2 and FMA using a bazel compile such as:
```
bazel build -c opt --copt=-march=native //tensorflow:libtensorflow.so OR
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=opt //tensorflow:libtensorflow.so
```
Each time I recompile I have a tensorflow which Julia loads and appears to be happy with, but when I run `Pkg.test("tensorflow")` part of the output is:
```
...
Test Summary:   | Pass  Total
shape_inference |  255    255
2018-06-07 16:15:10.068801: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
TensorBoard 1.8.0 at http://linux-k18k.suse:6006 (Press CTRL+C to quit)
Test Summary: |
show          | No tests
...
```
I'm thinking that either I don't have the compile options right, or the Julia test is not giving a correct hint about how the library was compiled.

**Comment by oxinabox** [comment]
> I'm thinking that either I don't have the compile options right, 

If I am recalling correctly:
```
bazel build -c opt --copt=-march=native //tensorflow:libtensorflow.so
```
is correct.


> or the Julia test is not giving a correct hint about how the library was compiled.

That message doesn't come from any julia code, it comes from libtensorflow.so itself, when julia invokes it.


---

My theory would be that julia is not hitting the right libtensorflow.so.
TensorFlow.jl automatically installed the official (and non-machine optimized) libtensorflow when it is added.

You need to tell it to hit your custom compiled one.

See 
http://malmaud.github.io/TensorFlow.jl/latest/build_from_source.html#Step-2:-Install-the-TensorFlow-binary-1

**Comment by colbec** [comment]
Yes, I am using the ENV["TENSORFLOW"] variable to point directly into the bazel-bin version just compiled.
Now when I have this variable set, if I try to build tensorflow in Julia again the build ignores this setting and goes ahead and downloads the latest official. At this point it seems to revert to the version just downloaded even if the ENV is still set. Since I am now pointed at the official, when I try to test tensorflow of course it complains on startup that not only are AVX2 and FMA missing but also a bunch of SSE varieties, and then later in the test produces the warning I mentioned before.
So after restarting Julia and setting the ENV to point at the bazel-bin again the complaint on starting test disappears but the warning about AVX2 and FMA repeats.
It's all very puzzling. If I can get the symptoms to repeat reliably I will try a question in the tensorflow repo.

**Comment by colbec** [comment]
Thanks, indeed I was using ENV["TENSORFLOW"]. When I change it to "LIBTENSORFLOW" using tensorflow seems ok but:
```
Pkg.test("TensorFlow")
INFO: Testing TensorFlow
ERROR: LoadError: LoadError: could not load library "~/.julia/v0.6/TensorFlow/deps/"
~/.julia/v0.6/TensorFlow/deps/.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(::String, ::UInt32) at ./libdl.jl:97
 [2] TensorFlow.Graph() at /home/colin/.julia/v0.6/TensorFlow/src/core.jl:21
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] process_options(::Base.JLOptions) at ./client.jl:305
 [8] _start() at ./client.jl:371
while loading /home/colin/.julia/v0.6/TensorFlow/test/../examples/logistic.jl, in expression starting on line 22
while loading /home/colin/.julia/v0.6/TensorFlow/test/runtests.jl, in expression starting on line 6

```
Even if I set 
`ENV["LIBTENSORFLOW"]="~/.julia/v0.6/TensorFlow/deps/"`
which would seem to fit with the quoted code I get file not found.
I see my ENV["LIB_BASE"] is empty. I will see what else I can discover.

**Comment by colbec** [comment]
Oops, I see LIB_BASE is a const and not an ENV. Sorry about that. Working...

**Comment by oxinabox** [comment]
Yep, LIB_BASE doesn't matter to you, it is only used it you don't have `LIBTENSORFLOW` set.
(`get`  takes the from `get(dict, key,  default_if_key_not_found)`)

You should be doing `ENV[LIBTENSORFLOW]` absolute path to the `libtensorflow.so` which was output by bazel. It should  be something like `/home/colbec/build/tensorflow/lib/libtensorflow.so`
(Roughly speaking, its been a while since I built libtensorflow from source I can't remeber the folder structure)

**Comment by colbec** [comment]
> You should be doing ENV[LIBTENSORFLOW] absolute path to the libtensorflow.so
Yes, that is what I am doing (with name of env variable in quotes) and this generates the "could not load library" error. The file is definitely there and it works, since if I copy the .so files to the Julia deps... directory and do not use the ENV then something loads up no problem.

```
INFO: Testing TensorFlow
ERROR: LoadError: LoadError: could not load library "~/Downloads/tensorflow/bazel-bin/tensorflow/libtensorflow.so"
~/Downloads/tensorflow/bazel-bin/tensorflow/libtensorflow.so: cannot open shared object file: No such file or directory
```
Since often there are multiple .so files in a library, this might mean that while it can find libtensorflow.so it can't find some associated file that it needs but does not specify in the error? I am copying up libtensorflow_framework.so.

**Comment by colbec** [comment]
My mistake was in thinking that Julia would be able to evaluate the tilde for the home directory.
Replacing the tilde with the full "/home/..." resolved that issue.
But the comment about AVX2 and FMA remains. I'm looking into it.

**Comment by colbec** [comment]
I found some helpful hints on how to approach this from site superuser.com.
If I can find an opcode in the libtensorflow.so that is unique to AVX2 for example then it must have been correctly compiled for those instructions, even if only conditionally executed.
Copying the libtensorflow.so into a working directory and running
```
objdump -d libtensorflow.so > oblist.txt
gawk 'BEGIN { IGNORECASE = 1 } /\<(VPSRLVD|VPSRLVQ)\>/' oblist.txt
```
where the first line extracts opcodes from the binary and the second searches for mentions of codes which I think are unique to AVX2 produces a list of about a dozen items.
So I think I can conclude I have successfully compiled AVX2 into the so binary even though tensorflow thinks it is missing, so I can safely stop worrying about having an incomplete binary.
I'm open to correction on this conclusion.

**Comment by oxinabox** [comment]
I think you need to make a report upstream.
https://github.com/tensorflow/tensorflow/issues/new

It sure looks to me like you are setting the right flags in your first post.
I wouldn't trust the presence of opt-codes to tell you if those ops are actually being executed.
I expect the CUP  feature gaurd will stop them being used on systems without support.
So seeing that warning mean they are not being used, I suspect


You'll want to include the info from: (only the first should matter, but they might want the others)

```
@show tf_version(kind=:backend) 
@show  tf_version(kind=:python)
@show  tf_version(kind=:julia)
```

Also link back to this issue for context.

They are not going to be able to help much with the julia library,
but this seems  to be a LibTensorFlow issue.

**Comment by colbec** [comment]
Hmm, the tensorboard git issues page specifies up front that tensorboard issues go in a different place.
In order to ensure asking the right question in the right place I explored the tensorboard avenue locally and find that indeed when I start tensorboard outside of Julia I get the AVX2 FMA message. So one possibility is that it is not tensorflow proper that has the issue.
When I attempt to access tensorboard server using `tensorboard --logdir=/tmp/tmph0TcsF` (which is the location given in INFO: when the tests start) tensorboard seems to start ok apart from the AVX2 message, but from Firefox I cannot access the server - FF reports "Server not found".
It's possible that just compiling the .so library misses a tensorboard component; I guess one option here is to recompile tensorflow as a full pip package, install into Python and try again.

**Comment by colbec** [comment]
OK tensorboard works without the full install, but the instruction for me to use the URL `http://linux-k18k.suse:6006` will only work if the local hosts file is set up to recognize that format. In my case `localhost:6006` does the job nicely and allows tensorboard to open normally but finds no data. I guess this is because no events have been written to the /tmp... location:
```
No dashboards are active for the current data set.
Probable causes:
    You haven’t written any data to your event files.
    TensorBoard can’t find your event files. 
```

**Comment by colbec** [comment]
The explanation from the tensorboard folks seems to put this to rest. The message is a by-product of other grander processes, but I think has minimal effect at this point.

**Comment by oxinabox** [comment]
Oh, sorry.
I didn't see the Tensorboard mention at the top.
If I had have, I could have told you:
The copy of tensorboard, and of python tensorflow that ships with TensorFlow.jl (via Conda.jl),
does not use the same libtensorflow.so as the main processes.
As the tensorboard folks said
it doesn't matter because they are not a performance critical part of the software.

I though you were getting that warning on every call to `Session()`

**Comment by colbec** [comment]
This error no longer happens with tensorboard 1.9.
