### ISSUE TITLE
Error using train.minimize

### ISSUE THREAD

**Issue by SamuelWiqvist** [malmaud/TensorFlow.jl#404]
I have installed TensorFlow.jl, and the basic usage example works well.

However, when I try to run the logistic regression example I get following error: 

![screenshot from 2018-06-20 15-54-42](https://user-images.githubusercontent.com/12857904/41662857-5295e1ee-74a2-11e8-8be5-81c1b7aa0708.png)

I get similar problems with train.minimize for the MNIST example as well.

TensorFlow itself  (i.e. the Python version) seems to work okay since I can run the Python version of the MNIST example. 

The system I use: 
![screenshot from 2018-06-20 15-57-23](https://user-images.githubusercontent.com/12857904/41663092-f028d60a-74a2-11e8-90b1-235cb1df3590.png)

TensorFlow.jl version:
![screenshot from 2018-06-20 15-59-11](https://user-images.githubusercontent.com/12857904/41663085-e989e23a-74a2-11e8-9c54-7e4a585d7614.png)

/ Samuel

**Comment by oxinabox** [comment]
Please run

```
@show tf_version(kind=:backend) 
@show  tf_version(kind=:python)
@show  tf_version(kind=:julia)
```

And also tell me if your did anything  even vaguely special with your install, e.g. using non-Conda python, or a custom LibTensorFlow

**Comment by oxinabox** [comment]
Oh you're running a fairly old version.
run `Pkg.update()`.

**Comment by SamuelWiqvist** [comment]
@oxinabox  Thanks for your fast reply!

I have now updated both TesorFlow and TensorFlow.jl, and I am currently at version 0.9.1 for TensorFlow.jl.

I did not use conda to install TensorFlow, I installed it using  pip3 instead.

However, I now get a different error when running `train.minimize`: 

![screenshot from 2018-06-20 17-06-01](https://user-images.githubusercontent.com/12857904/41667035-4284fef2-74ac-11e8-9ad2-b8dedd310e1d.png)

Outputs from `@show`: 

![screenshot from 2018-06-20 17-07-27](https://user-images.githubusercontent.com/12857904/41667109-7a293fbc-74ac-11e8-90da-697a924d9b07.png)

**Comment by oxinabox** [comment]
Hmm looks like your back-end version is wrong still.
It should have been updated to 1.8 when `Pkg.update()` was run.
(I though `Pkg.update()` triggers `Pkg.build` but maybe not).
You  should run `Pkg.build("TensorFlow")`, 


After that if it still isn't working,  can you run:
the script at  (cf #405)
https://gist.github.com/oxinabox/587932d4d197ff5fae72fb31fba9dad5
and paste in all the output?

**Comment by SamuelWiqvist** [comment]
I tried the same installation process on a different computer, and that worked fine. I, therefore, think I simply made some kind of mistake during the installation before. But the installation method itself seems to be working ok.

**Comment by oxinabox** [comment]
Cool, I am glad you got it sorted
