### ISSUE TITLE
Cannot use TensorFlow as it says Failed to precompile HDF5

### ISSUE THREAD

**Issue by ebbythomas** [malmaud/TensorFlow.jl#407]
Hi, I am finding trouble with using TensorFlow as I  keep on getting an error "Failed to precompile HDF5"..
Any suggestions..?

Ebby

**Comment by oxinabox** [comment]
I suggest attempting to `Pkg.add("HDF5"); Pkg.build("HDF5"); Pkg.test("HDF5")` 
That is the best place to start debugging.
You might need to open an issue at https://github.com/JuliaIO/HDF5.jl/

We depend on HDF5.jl (via JLD.jl) for saving and loading.
At some point in the future we might switch to JLD2.jl, or some other format, which wouldn't have the binary dependency HDF5.jl has, which might make it cause less problems for people.

**Comment by ebbythomas** [comment]
Thanks,
I can see that Pkg.test("HDF5") had test errors.
Now trying to work on that
Ebby
