### ISSUE TITLE
Tensors don't broadcast operations

### ISSUE THREAD

**Issue by lake-effect** [malmaud/TensorFlow.jl#429]
### error

```
julia> correct_prediction = argmax(y_conv, 2) .== argmax(y_, 2)
ERROR: TypeError: in _similar_for, in typeassert, expected Integer, got Tensor{Int32}
Stacktrace:
 [1] _similar_for(::UnitRange{Int64}, ::Type, ::Tensor{Int64}, ::Base.HasLength) at ./array.jl:532
 [2] _collect(::UnitRange{Int64}, ::Tensor{Int64}, ::Base.HasEltype, ::Base.HasLength) at ./array.jl:563
 [3] collect(::Tensor{Int64}) at ./array.jl:557
 [4] broadcastable(::Tensor{Int64}) at ./broadcast.jl:609
 [5] broadcasted(::Function, ::Tensor{Int64}, ::Tensor{Int64}) at ./broadcast.jl:1139
 [6] top-level scope at none:0
```

### environment

```
Wording: Please copy-paste the entirely of the below output into any bug reports.
Note that this may display some errors, depending upon on your configuration. This is fine.

----------------
Library Versions
----------------
$(Expr(:escape, :(ENV["TF_USE_GPU"]))) = "1"
Trying to evaluate ENV["LIBTENSORFLOW"] but got error: KeyError("LIBTENSORFLOW")

$(Expr(:escape, :(tf_version(kind=:backend)))) = v"1.8.0"
$(Expr(:escape, :(tf_version(kind=:python)))) = v"1.8.0"
$(Expr(:escape, :(tf_version(kind=:julia)))) = v"0.10.0"

-------------
Python Status
-------------
$(Expr(:escape, :(PyCall.conda))) = true
Trying to evaluate ENV["PYTHON"] but got error: KeyError("PYTHON")
$(Expr(:escape, :(PyCall.PYTHONHOME))) = "/home/ashley/.julia/packages/Conda/m7vem/deps/usr:/home/ashley/.julia/packages/Conda/m7vem/deps/usr"
Trying to evaluate readstring(#= /home/ashley/.julia/packages/TensorFlow/N0Fwu/src/version.jl:101 =# @cmd("pip --version")) but got error: UndefVarError(:readstring)
Trying to evaluate readstring(#= /home/ashley/.julia/packages/TensorFlow/N0Fwu/src/version.jl:102 =# @cmd("pip3 --version")) but got error: UndefVarError(:readstring)

------------
Julia Status
------------
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

```

**Comment by adamryczkowski** [comment]
I get the same error on the same line. You can be easily reproduced by

```
import TensorFlow
include(joinpath(dirname(dirname(pathof(TensorFlow))),"examples", "mnist_full.jl"))
```

**Comment by adamryczkowski** [comment]
Decorating the line with 

```
@tf
   argmax(y_conv, 2) .== argmax(y_, 2)
end
```

does not work either: `ERROR: UndefVarError: .== not defined`

**Comment by malmaud** [comment]
Ya, this should and can be fixed.

**Comment by adamryczkowski** [comment]
I would really like to help you, but I do not feel the developing of broadcast mechanism well enough, to implement it here. I claim that the few pages dedicated to the broadcast in the Julia's current manual (_Customizing broadcasting_) are some of the least clear. 

The manual does not explain what role exactly objects of type `BroadcastStyle` play. Names suggest they have something to do with the building of the iteration loop - I guess iterating over linear indices or using multidimensional array indexing - but that is only my guess, and I do not have a faint idea how to customize it (to e.g. to use row-major indexing for some custom types).

I also do not understand, why function with the name `similar` is used for allocation of the output container. Or maybe it is just a poor choice of a function name, and in this case, I would really like to know the history of choosing such a name. 

I also try to implement my own toy type to define custom broadcasting for them, but this effort is also hindered by poor (in my opinion) documentation; to really do a meaningful example of broadcasting, I feel that I need to define a type with my own range iterators. But alas, the interfaces (informal, of course) for all those abstract ancestors of `UnitRange` are undocumented...

**Comment by malmaud** [comment]
For the record, it was only `==` that wasn't broadcasting. If there are other operators that should broadcast which we're still missing, it's just a matter of adding a `@define_broadcast` call.

**Comment by oxinabox** [comment]
We can make everything broadcast now though.

everything

**Comment by malmaud** [comment]
Oh good point, ya.
