### ISSUE TITLE
MNIST Unsupported

### ISSUE THREAD

**Issue by smist09** [malmaud/TensorFlow.jl#436]
It appears the Julia package MNIST.jl hasn't been contributed to in years. Should the examples switch to MLDatasets.jl? This package seems to have some activity in Github. Currently I just get an error running the examples with the claim that the read method in MNIST.jl doesn't match a current prototype.

**Comment by malmaud** [comment]
Ya, a PR to make that change would be appreciated.

**Comment by oxinabox** [comment]
You need to fork the repo,
then push a branch to your fork (as a remote),
then make a PR from your fork to this one.

**Comment by malmaud** [comment]
Closed in https://github.com/malmaud/TensorFlow.jl/pull/437/files
