### ISSUE TITLE
Julia v1.0.0: installation issue  

### ISSUE THREAD

**Issue by askrix** [malmaud/TensorFlow.jl#441]
Dear Mr. Malmaud,

I thank you very much for your Julia wrapper of Google's "TensorFlow" library. I actually using Julia and TensorFlow for my master thesis. Everything was working fine till the last weekend. I upgraded my Julia installation from v.0.7.0 to v1.0.0. Since than I'm dealing the following error. Each time I'm trying to add TensorFlow to my Julia installation, the following error message occures:

Pkg.add("TensorFlow")
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package MNIST [d4533929]:
MNIST [d4533929] log:
├─possible versions are: 0.0.1-0.0.2 or uninstalled
├─restricted by julia compatibility requirements to versions: uninstalled
└─restricted by compatibility requirements with TensorFlow [1d978283] to versions: 0.0.2 — no versions left
   └─TensorFlow [1d978283] log:
     ├─possible versions are: [0.0.1, 0.1.0, 0.2.0-0.2.1, 0.3.0-0.3.1, 0.4.0-0.4.5, 0.5.0-0.5.1, 0.6.0-0.6.7, 0.7.0-0.7.5, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0-0.2.1, 0.3.0-0.3.1, 0.4.0-0.4.5, 0.5.0-0.5.1, 0.6.0-0.6.7, 0.7.0-0.7.5, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1]
     └─restricted by julia compatibility requirements to versions: 0.10.0-0.10.1 or uninstalled, leaving only versions: 0.10.0-0.10.1

Could you tell me how can I deal with this problem? Maybe I missing something?

Many thanks in advance!
Best regards,
Askrix

**Comment by oxinabox** [comment]
We fixed the problem with depending on MNIST.jl  the other day on master, 
so this should be fixed once a release is tagged

**Comment by askrix** [comment]
Many many thanks for the quick as a flash answer Mr. White! Could you say how much time will that require till the release is tagged?

**Comment by malmaud** [comment]
It's going to happen later today. You can always type `using Pkg; Pkg.dev("TensorFlow")` to use the `master` branch in the meanwhile.

**Comment by askrix** [comment]
Mr. Malmaud,

thank you very much for the answering my request. I'm sorry if my email seemed obtrusive. I used the command line you suggested but with a small correction, i.e. `using Pkg; Pkg.develop("TensorFlow")`. After the entering of this I saw the following output
`Cloning git-repo 'https://github.com/malmaud/TensorFlow.jl.git`
  Updating git-repo `https://github.com/malmaud/TensorFlow.jl.git`
 Resolving package versions...
 Installed JLD2 ─── v0.1.2
 Installed FileIO ─ v1.0.1
  Updating `~/.julia/environments/v1.0/Project.toml`
  [1d978283] + TensorFlow v0.10.1+ [`~/.julia/dev/TensorFlow`]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [15f4f7f2] + AutoHashEquals v0.2.0
  [8f4d0f93] + Conda v1.0.2
  [124859b0] + DataDeps v0.5.2
  [5789e2e9] + FileIO v1.0.1
  [92fee26a] + GZip v0.5.0
  [cd3eb016] + HTTP v0.7.0
  [83e8ac13] + IniFile v0.5.0
  [033835bb] + JLD2 v0.1.2
  [eb30cadb] + MLDatasets v0.3.0
  [739be429] + MbedTLS v0.6.2
  [3349acd9] + ProtoBuf v0.6.1
  [438e738f] + PyCall v1.18.4
  [1d978283] + TensorFlow v0.10.1+ [`~/.julia/dev/TensorFlow`]
  [81def892] + VersionParsing v1.1.3
  Building TensorFlow → `~/.julia/dev/TensorFlow/deps/build.log``
and respectively 
`using TensorFlow
[ Info: Precompiling TensorFlow [1d978283-2c37-5f34-9a8e-e9c0ece82495]
┌ Warning: Loading a new version of TensorFlow.jl for the first time. This initial load can take around 5 minutes as code is precompiled; subsequent usage will only take a few seconds.
└ @ TensorFlow ~/.julia/dev/TensorFlow/src/TensorFlow.jl:3`.
One thing of the output from `using TensorFlow` puzzles me a lot. In the previous version of the [documentation](https://malmaud.github.io/tfdocs/) you explained in the great detail how one can compile TensorFlow using bazel. Now this instruction  is not a part of the documentation. Is it not necessary anymore in order to gain the maximum of performance?

**Comment by oxinabox** [comment]
> In the previous version of the documentation you explained in the great detail how one can compile TensorFlow using bazel. Now this instruction is not a part of the documentation. Is it not necessary anymore in order to gain the maximum of performance?

No, it still is for maximum performance (though not so much if you are using g GPU I think).
We were supposed to delete just 1 step from the bazil instructions. Maybe we deleted whole page by mistake?

**Comment by malmaud** [comment]
The new version has been merged and no longer depends on MNIST.jl.
