### ISSUE TITLE
ERROR Julia 1.0 Colon has no name kwarg

### ISSUE THREAD

**Issue by byronbest** [malmaud/TensorFlow.jl#448]
ERROR: MethodError: no method matching (::Colon)(::Int64, ::Int64; name="ii")
Closest candidates are:
  Colon(::T<:Real, ::T<:Real) where T<:Real at range.jl:5 got unsupported keyword argument "name"
  Colon(::Real, ::Real) at range.jl:3 got unsupported keyword argument "name"
  Colon(::T<:Real, ::T<:Real, ::T<:Real) where T<:Real at range.jl:22 got unsupported keyword argument "name"
 
 [1] (::getfield(TensorFlow, Symbol("###14#15#16")){Colon,String})(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Int64, ::Vararg{Int64,N} where N) at /home/bbest/.julia/dev/TensorFlow/src/meta.jl:79

tf_version(kind=:julia) = 0.10.2+

-------------
Python Status
-------------
PyCall.conda = false
Trying to evaluate ENV["PYTHON"] but got error: KeyError("PYTHON")
PyCall.PYTHONHOME = /usr:/usr
String(read(#= /home/bbest/.julia/dev/TensorFlow/src/version.jl:104 =# @cmd("pip --version"))) = pip 18.0 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

String(read(#= /home/bbest/.julia/dev/TensorFlow/src/version.jl:105 =# @cmd("pip3 --version"))) = pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

------------
Julia Status
------------
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = /usr/bin/vi

**Comment by oxinabox** [comment]
Thanks for raising this 
I think this is the `@tf` macro screwing up somehow.

As a work around.
If you remove the `@tf` from the block then it should be fine, though you will loose the automatic node naming.

Can you post a MVE (pref) or at your original code?

Please use code formatting (look up how to format code in github)

**Comment by byronbest** [comment]
I was trying TensorFlow, using Mayo gene data, predicting Gleason Scores, code taken from
https://white.ucc.asn.au/2017/12/18/7-Binary-Classifier-Libraries-in-Julia.html




Definitely the @tf begin … for ii in 2:length(layer_sizes) — as that is the only Colon I can find nearby.
Thanks for your kind reply

**Comment by byronbest** [comment]
without the @tf macro, squeeze is no longer defined
changing to use dropdims ...

Now, it is failing in a function I wrote, before calling your function.

I have a parameter called "dir" passed to ready_data.

ERROR: MethodError: no method matching
joinpath(::TensorFlow.Tensor{Any}, ::String)
Closest candidates are:
  joinpath(::String, ::String) at path.jl:217
  joinpath(::AbstractString, ::AbstractString) at path.jl:226
  joinpath(::AbstractString, ::AbstractString, ::AbstractString...) at
path.jl:214
Stacktrace:
 [1] ready_data(::TensorFlow.Tensor{Any}) at
/datapool/sfu/predict_survival.jl:72


Line 72 is

    meta = CSV.read(joinpath(dir,"gs.csv"))

Modifying another function in the calling module? Wow
Can you please update your example to work in Julia 1.0?
I'm bailing for now.
-Byron

**Comment by oxinabox** [comment]
> without the @tf macro, squeeze is no longer defined

That is not likely.
The `@tf` macro does nothing to do with scope.
it only inserts names.

Please insert your code in codeblocks
when posting issues.

https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by oxinabox** [comment]
So the MWE for this error is:

```
using TensorFlow

@tf begin
    for ii in 1:10
    end
end
```

I can reproduce the error:

```
ERROR: MethodError: no method matching (::Colon)(::Int64, ::Int64; name="ii")
Closest candidates are:
  Colon(::T<:Real, ::T<:Real) where T<:Real at range.jl:5 got unsupported keyword argument "name"
  Colon(::Real, ::Real) at range.jl:3 got unsupported keyword argument "name"
  Colon(::T<:Real, ::T<:Real, ::T<:Real) where T<:Real at range.jl:22 got unsupported keyword argument "name"
  ...
Stacktrace:
 [1] (::getfield(TensorFlow, Symbol("###14#15#16")){Colon,String})(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Int64, ::Vararg{Int64,N} where N) at /home/wheel/oxinabox/.julia/dev/TensorFlow/src/meta.jl:79
 [2] (::getfield(TensorFlow, Symbol("##14#17")){getfield(TensorFlow, Symbol("###14#15#16")){Colon,String}})(::Int64, ::Vararg{Int64,N} where N) at /home/wheel/oxinabox/.julia/dev/TensorFlow/src/meta.jl:76
 [3] top-level scope at ./REPL[39]:2
```

**Comment by byronbest** [comment]
Good news, I wiped everything and checked out TensorFlow again.
I put the code into it’s own nested module, and changed the for loop to a while, and it works fine, or at the same accuracy as Linear and SVM anyway.

Honestly, it did complain about renaming an unrelated (read CSV) in the same module as the function containing the @tf macro, but that has gone away with the new update. It appeared to be inserting session as the first arg.

Thanks

**Comment by byronbest** [comment]
Note squeeze is called dropdims in Julia 1.0, this was just the next error found, after I removed the macro.
I noted that TensorFlow was doing stuff with squeeze, so I thought it was yours, although it was not defined.

**Comment by oxinabox** [comment]
> Note squeeze is called dropdims in Julia 1.0, this was just the next error found, after I removed the macro

Can you open another issue about this?
