### ISSUE TITLE
Multiple targeted sessions misplace node definitions

### ISSUE THREAD

**Issue by staticfloat** [malmaud/TensorFlow.jl#456]
When using multiple "targeted" `Session`s, (usecase: sending XLA streams to multiple remote `xrt_server` processes to make use of hardware accelerators not available on the host machine) I have found that TF.jl seemingly misplaces node definitions.  Here's a MWE:

```julia
using TensorFlow
pop!(Base.Multimedia.displays) # Work around Media.jl bug
sa = Session(Graph(); target="grpc://localhost:8470")
sb = Session(Graph(); target="grpc://localhost:8470")
run(sa, randn(1))
```

When run without the `sb` definition, things work just fine, and `run()` returns the 1-element vector.  When `sb` is defined however, the following error occurs:
```
julia> run(sa, randn(1))
ERROR: Tensorflow error: Status: FetchOutputs node Const:0: not found

Stacktrace:
 [1] check_status at /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/core.jl:377 [inlined]
 [2] macro expansion at /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/core.jl:18 [inlined]
 [3] run(::Session, ::Array{TensorFlow.Port,1}, ::Array{Any,1}, ::Array{TensorFlow.Port,1}, ::Array{Ptr{Nothing},1}) at
 /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/run.jl:95
 [4] run(::Session, ::Array{Tensor{Float64},1}, ::Dict{Any,Any}) at /home/staticfloat/.julia/packages/TensorFlow/kl0uH/
src/run.jl:210
 [5] run(::Session, ::Tensor{Float64}, ::Dict{Any,Any}) at /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/run.j
l:231
 [6] run(::Session, ::Tensor{Float64}) at /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/run.jl:239
 [7] run(::Session, ::Array{Float64,1}) at /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/run.jl:243
 [8] top-level scope at none:0
```

This can be verified by downloading [this tarball](https://github.com/JuliaPackaging/Yggdrasil/releases/tag/XRTServer-v2018.10.25), extracting it onto the local machine, and running `./bin/xrt_server`, which will open up an XRT endpoint on `localhost:8470`.

## `tf_versioninfo()` output

This is on a custom version of Julia and a custom version of `TensorFlow.jl`, but neither should have any impact on this, I don't think.  The custom version of `TensorFlow.jl` just [bundles a new TF binary that is custom-built](https://github.com/malmaud/TensorFlow.jl/compare/master...staticfloat:sf/xrt_server) with some patches to support our XRT/XLA work.  The custom version of Julia contains [various compiler improvements](https://github.com/JuliaLang/julia/compare/kf/tpu3).

```
julia> tf_versioninfo()
Wording: Please copy-paste the entirely of the below output into any bug reports.
Note that this may display some errors, depending upon on your configuration. This is fine.

----------------
Library Versions
----------------
Trying to evaluate ENV["TF_USE_GPU"] but got error: KeyError("TF_USE_GPU")
Trying to evaluate ENV["LIBTENSORFLOW"] but got error: KeyError("LIBTENSORFLOW")

tf_version(kind=:backend) = 1.12.0-rc0
Trying to evaluate tf_version(kind=:python) but got error: RemoteException(2, CapturedException(LoadError("/home/static
float/.julia/packages/TensorFlow/kl0uH/src/py.jl", 1, ArgumentError("Package PyCall not found in current path:\n- Run `
import Pkg; Pkg.add(\"PyCall\")` to install the PyCall package.\n")), Any[(require at loading.jl:823, 1), (include at b
oot.jl:317 [inlined], 1), (include_relative at loading.jl:1038, 1), (include at sysimg.jl:29, 1), (include at client.jl
:388, 1), (#3 at TensorFlow.jl:159, 1), (#116 at process_messages.jl:276, 1), (run_work_thunk at process_messages.jl:56
, 1), (run_work_thunk at process_messages.jl:65, 1), (#102 at task.jl:259, 1)]))
tf_version(kind=:julia) = 0.10.2+

-------------
Python Status
-------------
PyCall.conda = false
Trying to evaluate ENV["PYTHON"] but got error: KeyError("PYTHON")
PyCall.PYTHONHOME = /usr:/usr
String(read(#= /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/version.jl:104 =# @cmd("pip --version"))) = pip 9
.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

String(read(#= /home/staticfloat/.julia/packages/TensorFlow/kl0uH/src/version.jl:105 =# @cmd("pip3 --version"))) = pip
9.0.1 from /usr/lib/python3/dist-packages (python 3.6)


------------
Julia Status
------------
Julia Version 1.1.0-DEV.523
Commit 3f8d6c17b2 (2018-10-21 22:41 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

Pinging @keno because he might have something to say about this.

**Comment by Keno** [comment]
You need to set the default graph to match that of the session before you enqueue a node (`with_def_graph`). Doesn't look like there's currently a way to pass in the session explicitly upon construction.

**Comment by staticfloat** [comment]
Confirmed that wrapping things in `TensorFlow.as_default(graph) do ... end` works.

**Comment by oxinabox** [comment]
@staticfloat  are you fully clear on why this is happening?
Because the default graph is always the `Graph()` last constructed,
and becuase constants (like the output of `randn()`) are at some point coerced into constant tensors (`Const` ops) that need to live on some graph.

`run` only evalutes operations on a graph,
But the operation functions themselves (like `constant`),
put the nodes on the graph.

I am note sure at what point when one runs `run(sess, 5)` the `TensorFlow.constant(5)` gets called.
But it does occur, I think we might actually have a line saying

```
run(sess, x::Any) = run(sess, Tensor(x))
```

Which would do that.

**Comment by staticfloat** [comment]
Yes, thanks, I do understand.  I suppose really what I am unhappy about is that a `Graph` must be connected to a session immediately; it would make much more sense to me that a `Graph` would be independent of a `Session`, allowing you to generate ops that are floating off in space, completely un-executable until you instantiated the graph upon some session, at which point all of those ops would be put together on the session's execution context.  But I realize this is not up to TensorFlow.jl, this is just how TensorFlow works, and I'm more than willing to use the simple `as_default(graph) do` API.

**Comment by oxinabox** [comment]
>  I suppose really what I am unhappy about is that a Graph must be connected to a session immediately


I know what you mean, I think.
The Graph, Session separation seems weak
