### ISSUE TITLE
A doubt on TensorFlow.jl

### ISSUE THREAD

**Issue by ConAntares** [malmaud/TensorFlow.jl#472]
I am a beginner on deep learning with a small fundamental on Julia.
I have some doubts on this Julia API.
Does Julia API have a same performance than Python API for TensorFlow?
Why is Julia API so small(188KB)? Is it contains all the features than Python's TensorFlow?

**Comment by oxinabox** [comment]
Yes, it gas same performances as python.
Because both just call the C back-end.

It contains approximately all the features of the python API excluding the contrib submodule.

**Comment by oxinabox** [comment]
> when will we could use this API on windows system? 

When someone submits a PR to add windows support.
(It will not come from me, as I do not do dev on Windows.)
I spent day trying to debug why it wasn't working a year or so back, and got nowhere
see https://github.com/malmaud/TensorFlow.jl/pull/302

**Comment by JulesGM** [comment]
I was wondering, how does the performance compares to just importing python tensorflow with PyCall?

**Comment by oxinabox** [comment]
It logically should be better.
But only up to a costantish factor.
since the rework happens in the C API.
