### ISSUE TITLE
Elementwise equality gives unusual results

### ISSUE THREAD

**Issue by briandepasquale** [malmaud/TensorFlow.jl#473]
I implemented the MLP MNIST [example](https://malmaud.github.io/tfdocs/tutorial/) but the following definition gave unexpected results:

`correct_prediction = indmax(y_conv, 2)  .==  indmax(y_, 2)`.

I had to use the native TensorFlow function `equal` to get the desired result:

`correct_prediction = equal(indmax(y_conv, 2), indmax(y_, 2))`.

Is the tutorial outdated, or is my version of Julia outdated (0.6)? Thanks.

**Comment by malmaud** [comment]
Your version of Julia is outdated. Julia is up to 1.0 now.
