### ISSUE TITLE
Release 0.10.3 not in registry

### ISSUE THREAD

**Issue by marcoct** [malmaud/TensorFlow.jl#486]
I noticed that the latest tagged release (0.10.3 from October 2018) is not in the General registry:

https://github.com/JuliaRegistries/General/blob/master/T/TensorFlow/Versions.toml

Is this intentional?

This came up because I am also encountering the errors in https://github.com/malmaud/TensorFlow.jl/issues/484. I was able to easily set up an simple environment in which the TensorFlow.jl tests pass with TensorFlow.jl version 0.10.3 (using e.g. `add TensorFlow#8a28acb`), but I wasn't able to easily get a working environment in which the tests pass with version 0.10.2. I am depending on TensorFlow.jl from another package and having a version number to depend on would be great.

**Comment by malmaud** [comment]
OK, 0.10.4 is now registered.
