### ISSUE TITLE
FYI: Support TF v1.12.2 that "Fixes a potential security vulnerability where carefully crafted GIF images can produce a null pointer dereference during decoding"

### ISSUE THREAD

**Issue by PallHaraldsson** [malmaud/TensorFlow.jl#504]
I'm not sure what "Updated TF Python version to 1.13.1" refers to. Is it a typo for 1.12.1 or some other version number?

**Comment by PallHaraldsson** [comment]
I suppose the typo is at the official site, where they should say 1.13.2 (that you want to support; eventually):

https://github.com/tensorflow/tensorflow/issues/28439

**Comment by mihaimaruseac** [comment]
TensorFlow 1.13 and 1.12.2 both have the fix for that security vulnerability.

**Comment by mihaimaruseac** [comment]
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2019-001.md
