### ISSUE TITLE
Tensorflow 2.0 API branch?

### ISSUE THREAD

**Issue by holmescn** [malmaud/TensorFlow.jl#509]
Since Tensorflow 2.0 API is in beta stage, is there a plan to open a branch for the new coming API?

**Comment by oxinabox** [comment]
It is already done, and is included in release 0.12.0

Note that TensorFlow 2.0 and TensorFlow Eager mode are for all intents (API wise) the same thing

Docs are at
https://github.com/malmaud/TensorFlow.jl/blob/master/docs/src/eager_mode.md
