### ISSUE TITLE
Pkg.build() issue

### ISSUE THREAD

**Issue by ViralBShah** [malmaud/TensorFlow.jl#6]
I think I had installed tensorflow using pip before. Also, with brew, I no longer need to use `sudo` for `pip`. If possible, I would personally prefer to install tensorflow binaries separately, rather than going through `Pkg.build()`, given the number of ways one might do so. Alternately the `build()` could detect the existence and give an appropriate error message to uninstall.

```
INFO: Building TensorFlow
Archive:  /Users/viral/.julia/v0.6/TensorFlow/deps/downloads/tensorflow.zip
  inflating: libc_api.so             
  inflating: libtensorflow.so        
  inflating: tensorflow-0.10.0rc0-py2-none-any.whl  
sudo: no tty present and no askpass program specified
=============================[ ERROR: TensorFlow ]==============================

LoadError: failed process: Process(`sudo pip install tensorflow-0.10.0rc0-py2-none-any.whl`, ProcessExited(1)) [1]
while loading /Users/viral/.julia/v0.6/TensorFlow/deps/build.jl, in expression starting on line 34

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: TensorFlow had build errors.

 - packages with build errors remain installed in /Users/viral/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("TensorFlow")`
 - build a single package by running its `deps/build.jl` script

================================================================================

```

**Comment by ViralBShah** [comment]
Despite this error message, I am able to run the example in the README.

**Comment by malmaud** [comment]
Ya, I still have to work on how to get the Python tensorflow installed smoothly during the build process. I think ideally, it would install tensorflow to a local miniconda installation as to not make any assumptions about the user's system's Python setup. 

Also, the dependency on the Python tensorflow is only temporary until Google adds a gradient-calculating API to the C library, which they said would happen soon.

**Comment by ViralBShah** [comment]
That would be perfect!

**Comment by malmaud** [comment]
Fixed in https://github.com/malmaud/TensorFlow.jl/commit/94d68f7dd1cad72c5da9a46905fa24ae76598182
