### ISSUE TITLE
Segfault due to empty tensor attribute

### ISSUE THREAD

**Issue by MikeInnes** [malmaud/TensorFlow.jl#79]
e.g.

``` julia
get_shape(Tensor(Int32[]))
```

I narrowed this down to the `TF_OperationGetAttrTensor` which tries to load the empty `RawTensor` as the `"value"` attribute of the `"Const"` op, but I'm not sure where to go from there. Empty `RawTensor`s seem to be created just fine and the code for setting them as an attribute of a `NodeDescription` seems too simple to be at fault.

**Comment by malmaud** [comment]
Hmm, this is stumping me atm. We don't seem to be doing anything wrong. Could be a genuine bug with TensorFlow.

**Comment by malmaud** [comment]
I filed an issue: https://github.com/tensorflow/tensorflow/issues/7394
