### ISSUE TITLE
Document how to use QueueRunner?

### ISSUE THREAD

**Issue by kshyatt** [malmaud/TensorFlow.jl#93]
An example would be really cool.

**Comment by malmaud** [comment]
Ya, agreed. I think I can get to it in the next week or so.

**Comment by kshyatt** [comment]
Bump.

**Comment by staticfloat** [comment]
Bump.

**Comment by malmaud** [comment]
QueueRunners have been almost entirely replaced in upstream TensorFlow by the dataset API, so I don't plan on exposing this interface anymore.
