### ISSUE TITLE
pyimport("tensorflow") exception in Atom

### ISSUE THREAD

**Issue by baggepinnen** [malmaud/TensorFlow.jl#94]
I'm using Atom for Julia developement. Unfortunately, I seem to have an issue using TensorFlow from within Atom. When using julia and tensorflow from the terminal everything is OK. `using TensorFlow` in Atom however throws an exception on the line `pyimport("tensorflow")` with the following text
```
PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('libcudart.so.7.5: cannot open shared object file: No such file or directory',)
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)

 in pyerr_check at /local/home/fredrikb/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /local/home/fredrikb/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /local/home/fredrikb/.julia/v0.5/P...
```

For TensorFlow to work in the regular terminal, I had to set my LD_LIBRARY_PATH such that TensorFlow could find the file `libcudart.so.7.5`. Any ideas on whether I have to somehow do this from Atom as well, or the problem lies elsewhere?

**Comment by malmaud** [comment]
Yes, if you need `LD_LIBRARY_PATH` to be set from the terminal, you're also going to need it to be set in Atom. I think if you set LD_LIBRARY_PATH in the terminal and then launch Atom, Atom will inherit the environment variable, but I'm not sure.

**Comment by malmaud** [comment]
I'll close this since it's not an issue in the scope of this package to resolve.
