### ISSUE TITLE
Thoughts on higher-level abstractions?

### ISSUE THREAD

**Issue by IainNZ** [malmaud/TensorFlow.jl#96]
So I think tf.slim is becoming more canonical for TF now (I think its tf.learn now?), but I was wondering if you were planning on including that machinery here or just leaving it for other packages to implement on top of TF.jl?

**Comment by malmaud** [comment]
Ya, it would be good to include it here. Not sure when I'd be able to get around to it personally, though.

**Comment by IainNZ** [comment]
Was more thinking about whether you even wanted a "canonical" higher level abstraction in here, or separated out. I think TF have accepted slim/learn as that, despite their original plan to keep it separate. Julia + TF came up at work so it got me thinking.
