### ISSUE TITLE
Docs for `run` are for `Base.run`

### ISSUE THREAD

**Issue by oxinabox** [malmaud/TensorFlow.jl#99]
the docs [here](https://malmaud.github.io/tfdocs/core/#Base.run)
read:

>  Base.run — Function.
> `run(command)`
> Run a command object, constructed with backticks. Throws an error if anything goes wrong, including the process exiting with a non-zero status.

which is not relevant.

**Comment by malmaud** [comment]
Good catch. I'll see about tweaking the automated doc-generating system to avoid that.

**Comment by malmaud** [comment]
Fixed now
